# Generated by Django 4.2.30 on 2026-05-27 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_product_requires_expiration_lot_and_more"),
        ("alerts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="catalog.lot",
            ),
        ),
    ]
