# Generated by Django 4.2.30 on 2026-05-31 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0003_alert_lot"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="category",
            field=models.CharField(
                choices=[
                    ("STOCK", "Stock"),
                    ("EXPIRATION", "Vencimiento"),
                    ("LOCATION", "Ubicación"),
                    ("INTEGRITY", "Integridad"),
                    ("BUSINESS", "Negocio"),
                ],
                default="STOCK",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="severity",
            field=models.CharField(
                choices=[
                    ("CRITICAL", "Crítico"),
                    ("HIGH", "Alto"),
                    ("MEDIUM", "Medio"),
                    ("LOW", "Bajo"),
                    ("INFO", "Informativo"),
                ],
                default="MEDIUM",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("LOW_STOCK", "Stock bajo mínimo"),
                    ("EXPIRATION_30", "Vencimiento en 30 días"),
                    ("EXPIRATION_60", "Vencimiento en 60 días"),
                    ("LOT_EXPIRED", "Lote vencido"),
                    ("COLD_CHAIN_MISSING", "Cadena de frío irregular"),
                    ("LOCATION_BLOCKED_WITH_STOCK", "Ubicación bloqueada con stock"),
                    ("STOCK_MISMATCH", "Desincronización stock vs ledger"),
                    ("STOCK_ZERO", "Producto sin stock"),
                ],
                max_length=64,
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["severity", "is_resolved"],
                name="alerts_aler_severit_3cdbdc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["category", "is_resolved"],
                name="alerts_aler_categor_a3b1c0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["is_resolved", "created_at"],
                name="alerts_aler_is_reso_3c2935_idx",
            ),
        ),
    ]
