# Generated by Django 5.2.15 on 2026-06-15 16:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0004_add_severity_category_indexes"),
        ("catalog", "0018_remove_is_active_from_productcombo"),
        ("inventory", "0011_add_deleted_at_to_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["product", "alert_type", "is_resolved"],
                name="alerts_aler_product_597c3f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["product", "location", "alert_type", "is_resolved"],
                name="alerts_aler_product_cd91ea_idx",
            ),
        ),
    ]
