# Generated by Django 4.2.30 on 2026-06-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchasing", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="purchaseorder",
            new_name="purchasing__status_b65bdb_idx",
            old_name="purchasing_po_status_created_idx",
        ),
        migrations.RenameIndex(
            model_name="purchaseorder",
            new_name="purchasing__supplie_dddc8a_idx",
            old_name="purchasing_po_supplier_status_idx",
        ),
        migrations.RenameIndex(
            model_name="purchaseorder",
            new_name="purchasing__number_b81c9d_idx",
            old_name="purchasing_po_number_idx",
        ),
        migrations.RenameIndex(
            model_name="reception",
            new_name="purchasing__purchas_7e8ba3_idx",
            old_name="purchasing_reception_po_status_idx",
        ),
        migrations.RenameIndex(
            model_name="reception",
            new_name="purchasing__receive_a626f7_idx",
            old_name="purchasing_reception_rcvby_conf_idx",
        ),
        migrations.RenameIndex(
            model_name="supplier",
            new_name="purchasing__nit_de2e7e_idx",
            old_name="purchasing_supplier_nit_idx",
        ),
        migrations.RenameIndex(
            model_name="supplier",
            new_name="purchasing__is_acti_7152f4_idx",
            old_name="purchasing_supplier_active_name_idx",
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="expected_delivery",
            field=models.DateField(
                blank=True,
                help_text="Fecha estimada de llegada de la mercancía.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="receptionitem",
            name="lot_expiration_date",
            field=models.DateField(
                blank=True,
                help_text="Fecha de vencimiento del lote recibido.",
                null=True,
            ),
        ),
    ]
