# Generated by Django 4.2.30 on 2026-06-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchasing", "0003_remove_supplier_contacto_supplier_pais_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="pais",
            field=models.CharField(max_length=100),
        ),
    ]
