# Generated by Django 4.2.30 on 2026-06-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchasing", "0005_receptionitemallocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="receptionitem",
            name="serial_number",
            field=models.CharField(
                blank=True,
                help_text="BR-04: Número de serie (obligatorio si la categoría lo exige).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="receptionitemallocation",
            name="serial_number",
            field=models.CharField(
                blank=True,
                help_text="BR-04: Número de serie (obligatorio si la categoría lo exige).",
                max_length=100,
                null=True,
            ),
        ),
    ]
