# Generated by Django 4.2.30 on 2026-06-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchasing", "0006_add_serial_number_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Soft delete timestamp. NULL = activo; not-NULL = eliminado lógicamente.",
                null=True,
            ),
        ),
    ]
