# Generated by Django 5.2.15 on 2026-06-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0018_remove_is_active_from_productcombo"),
        ("movements", "0012_invoice_customer_id_number_invoice_invoice_type_and_more"),
        ("purchasing", "0007_add_deleted_at_to_supplier"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="purchaseorderitem",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="receptionitem",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderitem",
            constraint=models.UniqueConstraint(
                fields=("purchase_order", "product"), name="uniq_po_item_product"
            ),
        ),
        migrations.AddConstraint(
            model_name="receptionitem",
            constraint=models.UniqueConstraint(
                fields=("reception", "purchase_order_item"), name="uniq_reception_item"
            ),
        ),
    ]
