# Generated by Django 5.2.4 on 2026-05-04 23:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_number", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Contador de factura",
                "verbose_name_plural": "Contadores de factura",
            },
        ),
        migrations.CreateModel(
            name="Movement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Entrada"),
                            ("SALIDA_VENTA_MAYOR", "Salida venta mayor"),
                            ("SALIDA_VENTA_MENOR", "Salida venta menor"),
                            ("SALIDA_DANO", "Salida por daño"),
                            ("SALIDA_VENCIMIENTO", "Salida por vencimiento"),
                            ("TRASLADO", "Traslado interno"),
                            ("AJUSTE", "Ajuste"),
                            ("DEVOLUCION", "Devolución"),
                        ],
                        max_length=32,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "stock_previo_origen",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "stock_resultante_origen",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "stock_previo_destino",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "stock_resultante_destino",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "quantity_invoiced",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("discrepancy_note", models.TextField(blank=True, null=True)),
                ("justification", models.TextField(blank=True, null=True)),
                (
                    "scanned_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("order_sku", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "invoice_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="invoices/%Y/%m/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "destination_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_movements",
                        to="inventory.location",
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements_executed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "origin_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_movements",
                        to="inventory.location",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="catalog.product",
                    ),
                ),
                (
                    "related_movement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="correction_links",
                        to="movements.movement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento",
                "verbose_name_plural": "Movimientos",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["product", "movement_type", "created_at"],
                        name="movements_m_product_b95046_idx",
                    ),
                    models.Index(
                        fields=["executed_by", "created_at"],
                        name="movements_m_execute_dab7c2_idx",
                    ),
                    models.Index(
                        fields=["origin_location", "created_at"],
                        name="movements_m_origin__c15a0f_idx",
                    ),
                    models.Index(
                        fields=["destination_location", "created_at"],
                        name="movements_m_destina_68fa5f_idx",
                    ),
                    models.Index(
                        fields=["invoice_number"], name="movements_m_invoice_c64326_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("invoice_number__isnull", False),
                            models.Q(("invoice_number", ""), _negated=True),
                        ),
                        fields=("invoice_number",),
                        name="uniq_movement_invoice_number_when_set",
                    )
                ],
            },
        ),
    ]
