# Generated by Django 4.2.30 on 2026-05-27 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_product_requires_expiration_lot_and_more"),
        ("movements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movement",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="catalog.lot",
            ),
        ),
        migrations.AlterField(
            model_name="movement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("ENTRADA", "Entrada"),
                    ("SALIDA_VENTA_MAYOR", "Salida venta mayor"),
                    ("SALIDA_VENTA_MENOR", "Salida venta menor"),
                    ("SALIDA_DANO", "Salida por daño"),
                    ("SALIDA_VENCIMIENTO", "Salida por vencimiento"),
                    ("TRASLADO", "Traslado interno"),
                    ("AJUSTE", "Ajuste"),
                    ("DEVOLUCION", "Devolución"),
                    ("SALIDA_COMBO", "Salida por combo"),
                ],
                max_length=32,
            ),
        ),
    ]
