# Generated by Django 4.2.30 on 2026-06-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movements", "0006_add_invoice_model"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="invoice",
            new_name="movements_i_number_dec47a_idx",
            old_name="movements_invoice_number_idx",
        ),
        migrations.RenameIndex(
            model_name="invoice",
            new_name="movements_i_issued__1c2329_idx",
            old_name="movements_invoice_issued_idx",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
