# Generated by Django 5.2.15 on 2026-06-15 16:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0018_remove_is_active_from_productcombo"),
        ("inventory", "0011_add_deleted_at_to_location"),
        ("movements", "0008_migrate_serials_to_productserial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="movement",
            index=models.Index(
                fields=["product", "origin_location"],
                name="movements_m_product_c8984b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="movement",
            index=models.Index(
                fields=["product", "destination_location"],
                name="movements_m_product_344b85_idx",
            ),
        ),
    ]
