# Generated by Django 5.2.15 on 2026-06-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movements", "0010_extend_invoice_billing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="customer_id_number",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="invoice_type",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="is_voided",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="void_reason",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="voided_at",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="voided_by",
        ),
        migrations.AlterField(
            model_name="movement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("ENTRADA", "Entrada"),
                    ("SALIDA_VENTA_MAYOR", "Salida venta mayor"),
                    ("SALIDA_VENTA_MENOR", "Salida venta menor"),
                    ("SALIDA_DANO", "Salida por daño"),
                    ("SALIDA_VENCIMIENTO", "Salida por vencimiento"),
                    ("TRASLADO", "Traslado interno"),
                    ("AJUSTE", "Ajuste"),
                    ("DEVOLUCION", "Devolución"),
                    ("SALIDA_COMBO", "Salida por combo"),
                ],
                max_length=32,
            ),
        ),
    ]
