"""
Datos estaticos del seed ICM.

Catalogo basado en Clasificacion_Productos.xlsx (fuente de verdad).
Las categorias y SKUs del Excel se conservan; los unicos ajustes son:
  - MPC-01A -> MPCA-1, MPC-02A -> MPCA-2 (letra sufijo invalida)
  - EC-01b  -> ECB-1                        (letra sufijo invalida)
  - S/C x2  -> FL-1, FL-2                  (sin codigo asignado)
Todos los precios en COP; exencion IVA para dispositivos medicos.
"""

from __future__ import annotations

from decimal import Decimal
from typing import Any

# ---------------------------------------------------------------------------
# Marcador de idempotencia para la fase de movimientos
# ---------------------------------------------------------------------------
SEED_MARKER_NIT = "900111222-3"

# ---------------------------------------------------------------------------
# Categorias — 11 hojas del Excel
# ---------------------------------------------------------------------------
CATEGORIES: list[dict[str, Any]] = [
    {
        "slug": "electroterapia",
        "name": "Electroterapia",
        "description": "Equipos de electroterapia para fisioterapia clinica.",
        "requires_serial_number": True,
        "is_returnable": True,
    },
    {
        "slug": "masajeadores",
        "name": "Masajeadores",
        "description": "Dispositivos de masaje terapeutico y recuperacion.",
        "requires_serial_number": False,
        "is_returnable": False,
    },
    {
        "slug": "bandas",
        "name": "Bandas",
        "description": "Bandas elasticas y mallas de resistencia graduada.",
        "requires_serial_number": False,
        "is_returnable": False,
    },
    {
        "slug": "cintas",
        "name": "Cintas",
        "description": "Cintas deportivas kinesiotape y vendaje funcional.",
        "requires_serial_number": False,
        "is_returnable": False,
    },
    {
        "slug": "pelotas",
        "name": "Pelotas",
        "description": "Pelotas terapeuticas, de gel y de equilibrio.",
        "requires_serial_number": False,
        "is_returnable": False,
    },
    {
        "slug": "agujas",
        "name": "Agujas",
        "description": "Agujas de puncion seca (APS) y acupuntura.",
        "requires_serial_number": False,
        "is_returnable": False,
    },
    {
        "slug": "accesorios",
        "name": "Accesorios",
        "description": "Accesorios, consumibles e instrumentos de medicion.",
        "requires_serial_number": False,
        "is_returnable": False,
    },
    {
        "slug": "camillas",
        "name": "Camillas",
        "description": "Camillas de masaje y quiropracticas.",
        "requires_serial_number": False,
        "is_returnable": False,
    },
    {
        "slug": "pedales",
        "name": "Pedales",
        "description": "Pedales ejercitadores para rehabilitacion.",
        "requires_serial_number": False,
        "is_returnable": False,
    },
    {
        "slug": "suelo-pelvico",
        "name": "Suelo Pelvico",
        "description": "Equipos para rehabilitacion de suelo pelvico.",
        "requires_serial_number": False,
        "is_returnable": False,
    },
    {
        "slug": "terapias-de-mano",
        "name": "Terapias de Mano",
        "description": "Materiales para terapia ocupacional y rehabilitacion de mano.",
        "requires_serial_number": False,
        "is_returnable": False,
    },
]

# ---------------------------------------------------------------------------
# Marcas (antes subcategorias) — (category_slug, brand_name, description)
# ---------------------------------------------------------------------------
SUBCATEGORIES: list[tuple[str, str, str]] = [
    # Electroterapia
    ("electroterapia", "ICM Therapy", "Equipos TENS/EMS/ultrasonido marca ICM Therapy"),
    ("electroterapia", "TensCare", "Electroestimuladores y TENS TensCare"),
    ("electroterapia", "Nu-Tek", "Equipos de electroterapia Nu-Tek"),
    ("electroterapia", "Dynatronics", "Ultrasonidos y combos Dynatronics"),
    # Masajeadores
    ("masajeadores", "ICM Therapy", "Masajeadores y herramientas de recuperacion ICM"),
    ("masajeadores", "WS Medical", "Pistolas de masaje percutivo WS Medical"),
    # Bandas
    ("bandas", "ICM Therapy", "Bandas elasticas y kits ICM Therapy"),
    ("bandas", "TheraBand", "Bandas precortadas resistencia graduada TheraBand"),
    ("bandas", "CanDo", "Mallas y bandas de resistencia CanDo"),
    # Cintas
    ("cintas", "ICM Therapy", "Cintas deportivas y kinesiotape ICM Therapy"),
    # Pelotas
    ("pelotas", "CanDo", "Pelotas de gel y resistencia CanDo"),
    ("pelotas", "Gymnic", "Balones de equilibrio y bousu Gymnic"),
    ("pelotas", "ICM Therapy", "Pelotas terapeuticas genericas ICM"),
    # Agujas
    ("agujas", "ICM Therapy", "Agujas de puncion seca y acupuntura"),
    # Accesorios
    ("accesorios", "ICM Therapy", "Accesorios y consumibles ICM Therapy"),
    ("accesorios", "Relief Pak", "Compresas frias/calientes y tanques Relief Pak"),
    ("accesorios", "Baseline", "Instrumentos de medicion y evaluacion Baseline"),
    ("accesorios", "Roscoe Medical", "Cables y accesorios TENS Roscoe Medical"),
    ("accesorios", "Thera Med", "Pads termicos profesionales Thera Med"),
    # Camillas
    ("camillas", "ICM Therapy", "Camillas terapeuticas y portatiles ICM"),
    # Pedales
    ("pedales", "ICM Therapy", "Pedales ejercitadores para miembros ICM"),
    # Suelo pelvico
    ("suelo-pelvico", "TensCare", "Ejercitadores de suelo pelvico TensCare"),
    ("suelo-pelvico", "KM Medical", "Estimuladores neuromusculares biofeedback KM"),
    # Terapias de mano
    ("terapias-de-mano", "CanDo", "Digiflex, plastilinas y accesorios CanDo"),
    ("terapias-de-mano", "ICM Therapy", "Plastilinas, fortalecedores y accesorios ICM"),
    ("terapias-de-mano", "Mano Robot", "Entrenadores roboticos de dedos Mano Robot"),
]

# ---------------------------------------------------------------------------
# Productos — catalogo completo ICM (Clasificacion_Productos.xlsx)
#
# Campos:
#   sku              : 1-4 letras, guion, 1-4 digitos  (unico)
#   name             : nombre del producto
#   category_slug    : slug de categoria
#   brand            : nombre de marca (debe estar en SUBCATEGORIES)
#   unit_cost        : costo de adquisicion (COP)
#   sale_price_retail: precio venta menor (COP)
#   sale_price_wholesale: precio venta mayor (COP)
#   tax_rate_pct     : 0.00 = exento, 19.00 = IVA general
#   reorder_point    : umbral minimo de reorden
#   requires_expiration: True para insumos con lote/vencimiento
# ---------------------------------------------------------------------------
PRODUCTS: list[dict[str, Any]] = [
    # ======================================================================
    # ELECTROTERAPIA — dispositivos (requires_serial_number en la categoria)
    # ======================================================================
    # --- TENS / EMS portatiles ---
    {
        "sku": "T-01",
        "name": "Tens Analogo 3000",
        "category_slug": "electroterapia",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("320000"),
        "sale_price_retail": Decimal("438000"),
        "sale_price_wholesale": Decimal("386000"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 3,
    },
    {
        "sku": "T-02",
        "name": "Tens Digital 7000",
        "category_slug": "electroterapia",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("420000"),
        "sale_price_retail": Decimal("575000"),
        "sale_price_wholesale": Decimal("506000"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 3,
    },
    {
        "sku": "T-05",
        "name": "Ems Digital 7500",
        "category_slug": "electroterapia",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("450000"),
        "sale_price_retail": Decimal("616000"),
        "sale_price_wholesale": Decimal("543000"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 2,
    },
    {
        "sku": "T-07",
        "name": "Intensity Twin Stim III Tens/Ems",
        "category_slug": "electroterapia",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("520000"),
        "sale_price_retail": Decimal("712000"),
        "sale_price_wholesale": Decimal("627000"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 2,
    },
    {
        "sku": "T-08",
        "name": "Twin Stim Plus 2nd Tens/Ems",
        "category_slug": "electroterapia",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("580000"),
        "sale_price_retail": Decimal("794000"),
        "sale_price_wholesale": Decimal("699000"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 2,
    },
    {
        "sku": "T-10",
        "name": "Twin Stim Plus 3ra Tens/Ems/If/Russian",
        "category_slug": "electroterapia",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("680000"),
        "sale_price_retail": Decimal("931000"),
        "sale_price_wholesale": Decimal("820000"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 2,
    },
    {
        "sku": "T-11",
        "name": "Caretec IV Digital Tens/Ems/If/Rs",
        "category_slug": "electroterapia",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("780000"),
        "sale_price_retail": Decimal("1068000"),
        "sale_price_wholesale": Decimal("941000"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 2,
    },
    {
        "sku": "T-13",
        "name": "Quattro 2.5 Clinical Electroestimulador Tens/Ems/If/Rs",
        "category_slug": "electroterapia",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("1850000"),
        "sale_price_retail": Decimal("2535000"),
        "sale_price_wholesale": Decimal("2233000"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 1,
    },
    {
        "sku": "T-14",
        "name": "Tens Digital Nu-Tek MT9000 Basico",
        "category_slug": "electroterapia",
        "brand": "Nu-Tek",
        "unit_cost": Decimal("380000"),
        "sale_price_retail": Decimal("520000"),
        "sale_price_wholesale": Decimal("458000"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 3,
    },
    {
        "sku": "TC-01",
        "name": "Sports TENS 2 Muscle Toning Pain Relief",
        "category_slug": "electroterapia",
        "brand": "TensCare",
        "unit_cost": Decimal("290000"),
        "sale_price_retail": Decimal("397000"),
        "sale_price_wholesale": Decimal("350000"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 3,
    },
    # --- Ultrasonidos ---
    {
        "sku": "UL-01",
        "name": "Ultrasonido Portatil US 1000 1Mhz",
        "category_slug": "electroterapia",
        "brand": "Dynatronics",
        "unit_cost": Decimal("880000"),
        "sale_price_retail": Decimal("1206000"),
        "sale_price_wholesale": Decimal("1062000"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 2,
    },
    {
        "sku": "UL-02",
        "name": "Ultrasonido Portatil US PRO 2000 1Mhz",
        "category_slug": "electroterapia",
        "brand": "Dynatronics",
        "unit_cost": Decimal("1100000"),
        "sale_price_retail": Decimal("1507000"),
        "sale_price_wholesale": Decimal("1328000"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 1,
    },
    {
        "sku": "UL-03",
        "name": "Ultrasonido Profesional Sound Care Plus 1Mhz-3Mhz",
        "category_slug": "electroterapia",
        "brand": "Dynatronics",
        "unit_cost": Decimal("1450000"),
        "sale_price_retail": Decimal("1987000"),
        "sale_price_wholesale": Decimal("1750000"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 1,
    },
    {
        "sku": "UL-05",
        "name": "Combocare E-Stim Ultrasound Combo Tens/Ems/If/Rs",
        "category_slug": "electroterapia",
        "brand": "Dynatronics",
        "unit_cost": Decimal("2200000"),
        "sale_price_retail": Decimal("3014000"),
        "sale_price_wholesale": Decimal("2656000"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 1,
    },
    {
        "sku": "UL-06",
        "name": "Ultrasonido Portatil Nu-Tek UT1032",
        "category_slug": "electroterapia",
        "brand": "Nu-Tek",
        "unit_cost": Decimal("950000"),
        "sale_price_retail": Decimal("1302000"),
        "sale_price_wholesale": Decimal("1147000"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 1,
    },
    {
        "sku": "UL-07",
        "name": "Ultrasonido Portatil Compass DU-3035",
        "category_slug": "electroterapia",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("920000"),
        "sale_price_retail": Decimal("1260000"),
        "sale_price_wholesale": Decimal("1110000"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 1,
    },
    # --- Otros equipos ---
    {
        "sku": "MGX-03",
        "name": "Magnetoterapia LaMagneto Pro",
        "category_slug": "electroterapia",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("1800000"),
        "sale_price_retail": Decimal("2466000"),
        "sale_price_wholesale": Decimal("2173000"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 1,
    },
    {
        "sku": "NB-05",
        "name": "Nebulizador Compresor ICMTHERAPY",
        "category_slug": "electroterapia",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("185000"),
        "sale_price_retail": Decimal("253000"),
        "sale_price_wholesale": Decimal("223000"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 3,
    },
    {
        "sku": "TP-04",
        "name": "Tanque Difusor de Parafina ICMTHERAPY 3 Lb",
        "category_slug": "electroterapia",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("320000"),
        "sale_price_retail": Decimal("438000"),
        "sale_price_wholesale": Decimal("386000"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 2,
    },
    # ======================================================================
    # ACCESORIOS ELECTROTERAPIA (de la hoja Electroterapia del Excel)
    # — sin serial; van a categoria accesorios
    # ======================================================================
    {
        "sku": "AC-01",
        "name": "Adaptador US 1000",
        "category_slug": "accesorios",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("42000"),
        "sale_price_retail": Decimal("57500"),
        "sale_price_wholesale": Decimal("50700"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 5,
    },
    {
        "sku": "AC-02",
        "name": "Adaptador US PRO 2000",
        "category_slug": "accesorios",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("42000"),
        "sale_price_retail": Decimal("57500"),
        "sale_price_wholesale": Decimal("50700"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 5,
    },
    {
        "sku": "AC-04",
        "name": "Adaptador Masajeador Pistola",
        "category_slug": "accesorios",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("38000"),
        "sale_price_retail": Decimal("52000"),
        "sale_price_wholesale": Decimal("45800"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 5,
    },
    {
        "sku": "CB-01",
        "name": "Juego De Cables Hembra Para Tens x 2 und Roscoe",
        "category_slug": "accesorios",
        "brand": "Roscoe Medical",
        "unit_cost": Decimal("38000"),
        "sale_price_retail": Decimal("52000"),
        "sale_price_wholesale": Decimal("45800"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 10,
    },
    {
        "sku": "CB-02",
        "name": "Cables Quattro 2.5",
        "category_slug": "accesorios",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("45000"),
        "sale_price_retail": Decimal("61600"),
        "sale_price_wholesale": Decimal("54300"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 8,
    },
    {
        "sku": "CB-04",
        "name": "Cabezal de Ultrasonido 1 cm Soundcare Plus",
        "category_slug": "accesorios",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("95000"),
        "sale_price_retail": Decimal("130000"),
        "sale_price_wholesale": Decimal("114600"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 3,
    },
    {
        "sku": "CB-05",
        "name": "Cabezal de Ultrasonido 5 cm Soundcare Plus",
        "category_slug": "accesorios",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("110000"),
        "sale_price_retail": Decimal("150700"),
        "sale_price_wholesale": Decimal("132800"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 3,
    },
    {
        "sku": "CB-06",
        "name": "Cable Conector SoundCare Rojo",
        "category_slug": "accesorios",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("28000"),
        "sale_price_retail": Decimal("38300"),
        "sale_price_wholesale": Decimal("33800"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 8,
    },
    {
        "sku": "CB-07",
        "name": "Cable Conector SoundCare/ComboCare",
        "category_slug": "accesorios",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("28000"),
        "sale_price_retail": Decimal("38300"),
        "sale_price_wholesale": Decimal("33800"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 8,
    },
    {
        "sku": "CB-08",
        "name": "Cables Hembra ICMTHERAPY Tens x 2 und",
        "category_slug": "accesorios",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("32000"),
        "sale_price_retail": Decimal("43800"),
        "sale_price_wholesale": Decimal("38600"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 10,
    },
    {
        "sku": "EL-01",
        "name": "Electrodos Adhesivos Cuadrados 5x5 cm",
        "category_slug": "accesorios",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("18000"),
        "sale_price_retail": Decimal("24600"),
        "sale_price_wholesale": Decimal("21700"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 20,
        "requires_expiration": True,
    },
    {
        "sku": "EL-04",
        "name": "Electrodo Adhesivo Rectangular 9x5 cm",
        "category_slug": "accesorios",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("22000"),
        "sale_price_retail": Decimal("30100"),
        "sale_price_wholesale": Decimal("26500"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 20,
        "requires_expiration": True,
    },
    {
        "sku": "GL-03",
        "name": "Gel Conductivo GL x 3785 ml",
        "category_slug": "accesorios",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("65000"),
        "sale_price_retail": Decimal("89000"),
        "sale_price_wholesale": Decimal("78500"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 8,
    },
    {
        "sku": "TH-02",
        "name": "Tanque Hidrocolector Relief Pak x6",
        "category_slug": "accesorios",
        "brand": "Relief Pak",
        "unit_cost": Decimal("85000"),
        "sale_price_retail": Decimal("116400"),
        "sale_price_wholesale": Decimal("102600"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 5,
    },
    # ======================================================================
    # MASAJEADORES
    # ======================================================================
    {
        "sku": "BMV-01",
        "name": "Bola de Masaje Vibrante",
        "category_slug": "masajeadores",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("68000"),
        "sale_price_retail": Decimal("93100"),
        "sale_price_wholesale": Decimal("82000"),
        "tax_rate_pct": Decimal("19.00"),
        "reorder_point": 5,
    },
    {
        "sku": "MDR-01",
        "name": "Masajeador de Rodilla",
        "category_slug": "masajeadores",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("95000"),
        "sale_price_retail": Decimal("130100"),
        "sale_price_wholesale": Decimal("114600"),
        "tax_rate_pct": Decimal("19.00"),
        "reorder_point": 4,
    },
    {
        "sku": "MPC-01",
        "name": "Masajeador de Piernas Compresor Aire Sencillo Talla M",
        "category_slug": "masajeadores",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("185000"),
        "sale_price_retail": Decimal("253400"),
        "sale_price_wholesale": Decimal("223300"),
        "tax_rate_pct": Decimal("19.00"),
        "reorder_point": 3,
    },
    {
        "sku": "MPCA-1",
        "name": "Masajeador de Piernas Compresor Aire Sencillo Talla L",
        "category_slug": "masajeadores",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("195000"),
        "sale_price_retail": Decimal("267100"),
        "sale_price_wholesale": Decimal("235300"),
        "tax_rate_pct": Decimal("19.00"),
        "reorder_point": 3,
    },
    {
        "sku": "MPC-02",
        "name": "Masajeador de Piernas y Brazos Compresor Aire Talla M",
        "category_slug": "masajeadores",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("245000"),
        "sale_price_retail": Decimal("335600"),
        "sale_price_wholesale": Decimal("295700"),
        "tax_rate_pct": Decimal("19.00"),
        "reorder_point": 2,
    },
    {
        "sku": "MPCA-2",
        "name": "Masajeador de Piernas y Brazos Compresor Aire Talla L",
        "category_slug": "masajeadores",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("255000"),
        "sale_price_retail": Decimal("349300"),
        "sale_price_wholesale": Decimal("307900"),
        "tax_rate_pct": Decimal("19.00"),
        "reorder_point": 2,
    },
    {
        "sku": "MPC-03",
        "name": "Masajeador con Compresor de Aire",
        "category_slug": "masajeadores",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("165000"),
        "sale_price_retail": Decimal("226000"),
        "sale_price_wholesale": Decimal("199200"),
        "tax_rate_pct": Decimal("19.00"),
        "reorder_point": 3,
    },
    {
        "sku": "MTP-001",
        "name": "Masajeador Tipo Pistola Frio/Calor WS-059",
        "category_slug": "masajeadores",
        "brand": "WS Medical",
        "unit_cost": Decimal("320000"),
        "sale_price_retail": Decimal("438400"),
        "sale_price_wholesale": Decimal("386400"),
        "tax_rate_pct": Decimal("19.00"),
        "reorder_point": 3,
    },
    {
        "sku": "MTP-002",
        "name": "Masajeador Tipo Pistola Calor WS-020",
        "category_slug": "masajeadores",
        "brand": "WS Medical",
        "unit_cost": Decimal("285000"),
        "sale_price_retail": Decimal("390400"),
        "sale_price_wholesale": Decimal("344000"),
        "tax_rate_pct": Decimal("19.00"),
        "reorder_point": 3,
    },
    {
        "sku": "MTP-003",
        "name": "Masajeador Tipo Pistola Sencillo WS-061",
        "category_slug": "masajeadores",
        "brand": "WS Medical",
        "unit_cost": Decimal("220000"),
        "sale_price_retail": Decimal("301300"),
        "sale_price_wholesale": Decimal("265600"),
        "tax_rate_pct": Decimal("19.00"),
        "reorder_point": 4,
    },
    {
        "sku": "CB-09",
        "name": "Cabezal Frio/Calor del Masajeador Pistola",
        "category_slug": "masajeadores",
        "brand": "WS Medical",
        "unit_cost": Decimal("35000"),
        "sale_price_retail": Decimal("47900"),
        "sale_price_wholesale": Decimal("42200"),
        "tax_rate_pct": Decimal("19.00"),
        "reorder_point": 8,
    },
    {
        "sku": "BH-01",
        "name": "Banera de Hielo Ice Tub",
        "category_slug": "masajeadores",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("85000"),
        "sale_price_retail": Decimal("116400"),
        "sale_price_wholesale": Decimal("102600"),
        "tax_rate_pct": Decimal("19.00"),
        "reorder_point": 3,
    },
    {
        "sku": "CH-01",
        "name": "Herramienta de Masaje con Hielo",
        "category_slug": "masajeadores",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("25000"),
        "sale_price_retail": Decimal("34200"),
        "sale_price_wholesale": Decimal("30200"),
        "tax_rate_pct": Decimal("19.00"),
        "reorder_point": 8,
    },
    {
        "sku": "BGM-02",
        "name": "Barra de Masaje en Y Rodillo Corporal",
        "category_slug": "masajeadores",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("28000"),
        "sale_price_retail": Decimal("38300"),
        "sale_price_wholesale": Decimal("33800"),
        "tax_rate_pct": Decimal("19.00"),
        "reorder_point": 6,
    },
    {
        "sku": "RY-01",
        "name": "Rodillo de Yoga Grande Gris/Negro 14x45cm",
        "category_slug": "masajeadores",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("38000"),
        "sale_price_retail": Decimal("52000"),
        "sale_price_wholesale": Decimal("45800"),
        "tax_rate_pct": Decimal("19.00"),
        "reorder_point": 5,
    },
    {
        "sku": "RY-03",
        "name": "Rodillo de Yoga Verde/Blanco 33cm",
        "category_slug": "masajeadores",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("28000"),
        "sale_price_retail": Decimal("38300"),
        "sale_price_wholesale": Decimal("33800"),
        "tax_rate_pct": Decimal("19.00"),
        "reorder_point": 6,
    },
    {
        "sku": "RY-04",
        "name": "Rodillo de Yoga Azul/Blanco 33cm",
        "category_slug": "masajeadores",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("28000"),
        "sale_price_retail": Decimal("38300"),
        "sale_price_wholesale": Decimal("33800"),
        "tax_rate_pct": Decimal("19.00"),
        "reorder_point": 6,
    },
    {
        "sku": "SHM-02",
        "name": "Set Herramienta de Masaje en Acero x 8 unidades",
        "category_slug": "masajeadores",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("120000"),
        "sale_price_retail": Decimal("164300"),
        "sale_price_wholesale": Decimal("144800"),
        "tax_rate_pct": Decimal("19.00"),
        "reorder_point": 3,
    },
    {
        "sku": "SHM-03",
        "name": "Set Herramienta de Masaje Manual Punto Gatillo x 3 unidades",
        "category_slug": "masajeadores",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("65000"),
        "sale_price_retail": Decimal("89000"),
        "sale_price_wholesale": Decimal("78500"),
        "tax_rate_pct": Decimal("19.00"),
        "reorder_point": 4,
    },
    # ======================================================================
    # BANDAS
    # ======================================================================
    {
        "sku": "BC-01",
        "name": "Set de Bandas De Latex Cerradas x 5 Colores",
        "category_slug": "bandas",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("32000"),
        "sale_price_retail": Decimal("43800"),
        "sale_price_wholesale": Decimal("38600"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 10,
    },
    {
        "sku": "BC-02",
        "name": "Set de Bandas Para Dedos x 5 unidades",
        "category_slug": "bandas",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("22000"),
        "sale_price_retail": Decimal("30100"),
        "sale_price_wholesale": Decimal("26500"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 12,
    },
    {
        "sku": "BOR-01",
        "name": "Bandas de Oclusion de Resistencia Brazos y Piernas",
        "category_slug": "bandas",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("68000"),
        "sale_price_retail": Decimal("93100"),
        "sale_price_wholesale": Decimal("82000"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 5,
    },
    {
        "sku": "BP-08",
        "name": "Banda Precortada Amarilla x 1.50m",
        "category_slug": "bandas",
        "brand": "TheraBand",
        "unit_cost": Decimal("8500"),
        "sale_price_retail": Decimal("11600"),
        "sale_price_wholesale": Decimal("10200"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 25,
    },
    {
        "sku": "BP-09",
        "name": "Banda Precortada Roja x 1.50m",
        "category_slug": "bandas",
        "brand": "TheraBand",
        "unit_cost": Decimal("9000"),
        "sale_price_retail": Decimal("12300"),
        "sale_price_wholesale": Decimal("10900"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 25,
    },
    {
        "sku": "BP-10",
        "name": "Banda Precortada Verde x 1.50m",
        "category_slug": "bandas",
        "brand": "TheraBand",
        "unit_cost": Decimal("9500"),
        "sale_price_retail": Decimal("13000"),
        "sale_price_wholesale": Decimal("11500"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 25,
    },
    {
        "sku": "BP-11",
        "name": "Banda Precortada Azul x 1.50m",
        "category_slug": "bandas",
        "brand": "TheraBand",
        "unit_cost": Decimal("10000"),
        "sale_price_retail": Decimal("13700"),
        "sale_price_wholesale": Decimal("12100"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 20,
    },
    {
        "sku": "BP-12",
        "name": "Banda Precortada Negra x 1.50m",
        "category_slug": "bandas",
        "brand": "TheraBand",
        "unit_cost": Decimal("10500"),
        "sale_price_retail": Decimal("14400"),
        "sale_price_wholesale": Decimal("12700"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 15,
    },
    {
        "sku": "BP-13",
        "name": "Banda Precortada Gris x 1.50m",
        "category_slug": "bandas",
        "brand": "TheraBand",
        "unit_cost": Decimal("11000"),
        "sale_price_retail": Decimal("15100"),
        "sale_price_wholesale": Decimal("13300"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 15,
    },
    {
        "sku": "BP-14",
        "name": "Banda Precortada Dorada x 1.50m",
        "category_slug": "bandas",
        "brand": "TheraBand",
        "unit_cost": Decimal("11500"),
        "sale_price_retail": Decimal("15700"),
        "sale_price_wholesale": Decimal("13900"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 10,
    },
    {
        "sku": "RLF-04",
        "name": "Rollo de Banda Azul x 45 Mts Latex Free",
        "category_slug": "bandas",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("75000"),
        "sale_price_retail": Decimal("102700"),
        "sale_price_wholesale": Decimal("90500"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 5,
    },
    {
        "sku": "RLF-05",
        "name": "Rollo de Banda Negro x 45 Mts Latex Free",
        "category_slug": "bandas",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("78000"),
        "sale_price_retail": Decimal("106800"),
        "sale_price_wholesale": Decimal("94100"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 5,
    },
    {
        "sku": "RLF-06",
        "name": "Rollo de Banda Gris x 45 Mts Latex Free",
        "category_slug": "bandas",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("78000"),
        "sale_price_retail": Decimal("106800"),
        "sale_price_wholesale": Decimal("94100"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 5,
    },
    {
        "sku": "RLF-07",
        "name": "Rollo de Banda Dorada x 45 Mts Latex Free",
        "category_slug": "bandas",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("82000"),
        "sale_price_retail": Decimal("112300"),
        "sale_price_wholesale": Decimal("98900"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 5,
    },
    {
        "sku": "MG-02",
        "name": "Malla Grande Amarilla 36cm",
        "category_slug": "bandas",
        "brand": "CanDo",
        "unit_cost": Decimal("12000"),
        "sale_price_retail": Decimal("16400"),
        "sale_price_wholesale": Decimal("14500"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 15,
    },
    {
        "sku": "MG-03",
        "name": "Malla Grande Roja 36cm",
        "category_slug": "bandas",
        "brand": "CanDo",
        "unit_cost": Decimal("12000"),
        "sale_price_retail": Decimal("16400"),
        "sale_price_wholesale": Decimal("14500"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 15,
    },
    {
        "sku": "MG-04",
        "name": "Malla Grande Verde 36cm",
        "category_slug": "bandas",
        "brand": "CanDo",
        "unit_cost": Decimal("13000"),
        "sale_price_retail": Decimal("17800"),
        "sale_price_wholesale": Decimal("15700"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 15,
    },
    {
        "sku": "MG-05",
        "name": "Malla Grande Azul 36cm",
        "category_slug": "bandas",
        "brand": "CanDo",
        "unit_cost": Decimal("13000"),
        "sale_price_retail": Decimal("17800"),
        "sale_price_wholesale": Decimal("15700"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 15,
    },
    {
        "sku": "MG-06",
        "name": "Malla Grande Negra 36cm",
        "category_slug": "bandas",
        "brand": "CanDo",
        "unit_cost": Decimal("14000"),
        "sale_price_retail": Decimal("19200"),
        "sale_price_wholesale": Decimal("16900"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 12,
    },
    {
        "sku": "MG-07",
        "name": "Malla Grande Doble Resistencia Amarilla/Verde 36cm",
        "category_slug": "bandas",
        "brand": "CanDo",
        "unit_cost": Decimal("16000"),
        "sale_price_retail": Decimal("21900"),
        "sale_price_wholesale": Decimal("19300"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 10,
    },
    {
        "sku": "MG-08",
        "name": "Malla Grande Doble Resistencia Azul/Roja 36cm",
        "category_slug": "bandas",
        "brand": "CanDo",
        "unit_cost": Decimal("16000"),
        "sale_price_retail": Decimal("21900"),
        "sale_price_wholesale": Decimal("19300"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 10,
    },
    {
        "sku": "MPQ-02",
        "name": "Malla Pequena Amarilla 18cm",
        "category_slug": "bandas",
        "brand": "CanDo",
        "unit_cost": Decimal("8000"),
        "sale_price_retail": Decimal("10900"),
        "sale_price_wholesale": Decimal("9600"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 20,
    },
    {
        "sku": "MPQ-03",
        "name": "Malla Pequena Roja 18cm",
        "category_slug": "bandas",
        "brand": "CanDo",
        "unit_cost": Decimal("8000"),
        "sale_price_retail": Decimal("10900"),
        "sale_price_wholesale": Decimal("9600"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 20,
    },
    {
        "sku": "MPQ-04",
        "name": "Malla Pequena Verde 18cm",
        "category_slug": "bandas",
        "brand": "CanDo",
        "unit_cost": Decimal("8500"),
        "sale_price_retail": Decimal("11600"),
        "sale_price_wholesale": Decimal("10200"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 20,
    },
    {
        "sku": "MPQ-05",
        "name": "Malla Pequena Azul 18cm",
        "category_slug": "bandas",
        "brand": "CanDo",
        "unit_cost": Decimal("8500"),
        "sale_price_retail": Decimal("11600"),
        "sale_price_wholesale": Decimal("10200"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 20,
    },
    {
        "sku": "MPQ-06",
        "name": "Malla Pequena Negra 18cm",
        "category_slug": "bandas",
        "brand": "CanDo",
        "unit_cost": Decimal("9000"),
        "sale_price_retail": Decimal("12300"),
        "sale_price_wholesale": Decimal("10900"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 15,
    },
    {
        "sku": "KBS-01",
        "name": "Kit de Bandas de Suspension TRX",
        "category_slug": "bandas",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("120000"),
        "sale_price_retail": Decimal("164300"),
        "sale_price_wholesale": Decimal("144800"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 3,
    },
    {
        "sku": "KRFS-01",
        "name": "BFR Kit de Restriccion de Flujo Sanguineo",
        "category_slug": "bandas",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("95000"),
        "sale_price_retail": Decimal("130100"),
        "sale_price_wholesale": Decimal("114600"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 4,
    },
    # ======================================================================
    # CINTAS
    # ======================================================================
    {
        "sku": "CD-01",
        "name": "Cinta Deportiva ICM Therapy Rosada",
        "category_slug": "cintas",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("8500"),
        "sale_price_retail": Decimal("11600"),
        "sale_price_wholesale": Decimal("10200"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 30,
    },
    {
        "sku": "CD-04",
        "name": "Cinta Deportiva ICM Therapy Verde",
        "category_slug": "cintas",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("8500"),
        "sale_price_retail": Decimal("11600"),
        "sale_price_wholesale": Decimal("10200"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 30,
    },
    # ======================================================================
    # PELOTAS
    # ======================================================================
    {
        "sku": "PFD-01",
        "name": "Pelota Fortalecedor Dedos y Manos 10 Lbs Azul",
        "category_slug": "pelotas",
        "brand": "CanDo",
        "unit_cost": Decimal("18000"),
        "sale_price_retail": Decimal("24600"),
        "sale_price_wholesale": Decimal("21700"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 10,
    },
    {
        "sku": "PGC-01",
        "name": "Pelota de Gel Circular 4.5cm Amarilla 15lbs",
        "category_slug": "pelotas",
        "brand": "CanDo",
        "unit_cost": Decimal("15000"),
        "sale_price_retail": Decimal("20500"),
        "sale_price_wholesale": Decimal("18100"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 12,
    },
    {
        "sku": "PGC-02",
        "name": "Pelota de Gel Circular 4.5cm Naranja 18lbs",
        "category_slug": "pelotas",
        "brand": "CanDo",
        "unit_cost": Decimal("15000"),
        "sale_price_retail": Decimal("20500"),
        "sale_price_wholesale": Decimal("18100"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 12,
    },
    {
        "sku": "PGC-03",
        "name": "Pelota de Gel Circular 4.5cm Verde 20lbs",
        "category_slug": "pelotas",
        "brand": "CanDo",
        "unit_cost": Decimal("16000"),
        "sale_price_retail": Decimal("21900"),
        "sale_price_wholesale": Decimal("19300"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 12,
    },
    {
        "sku": "PGC-04",
        "name": "Pelota de Gel Circular 4.5cm Roja 25lbs",
        "category_slug": "pelotas",
        "brand": "CanDo",
        "unit_cost": Decimal("16000"),
        "sale_price_retail": Decimal("21900"),
        "sale_price_wholesale": Decimal("19300"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 10,
    },
    {
        "sku": "PGC-05",
        "name": "Pelota de Gel Circular 4.5cm Azul 30lbs",
        "category_slug": "pelotas",
        "brand": "CanDo",
        "unit_cost": Decimal("17000"),
        "sale_price_retail": Decimal("23300"),
        "sale_price_wholesale": Decimal("20500"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 10,
    },
    {
        "sku": "PGO-01",
        "name": "Pelota de Gel Ovalada 6.5cm Amarilla 15lbs",
        "category_slug": "pelotas",
        "brand": "CanDo",
        "unit_cost": Decimal("18000"),
        "sale_price_retail": Decimal("24600"),
        "sale_price_wholesale": Decimal("21700"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 10,
    },
    {
        "sku": "PGO-02",
        "name": "Pelota de Gel Ovalada 6.5cm Naranja 18lbs",
        "category_slug": "pelotas",
        "brand": "CanDo",
        "unit_cost": Decimal("18000"),
        "sale_price_retail": Decimal("24600"),
        "sale_price_wholesale": Decimal("21700"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 10,
    },
    {
        "sku": "PGO-03",
        "name": "Pelota de Gel Ovalada 6.5cm Roja 25lbs",
        "category_slug": "pelotas",
        "brand": "CanDo",
        "unit_cost": Decimal("19000"),
        "sale_price_retail": Decimal("26000"),
        "sale_price_wholesale": Decimal("22900"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 10,
    },
    {
        "sku": "PGO-04",
        "name": "Pelota de Gel Ovalada 6.5cm Azul 30lbs",
        "category_slug": "pelotas",
        "brand": "CanDo",
        "unit_cost": Decimal("20000"),
        "sale_price_retail": Decimal("27400"),
        "sale_price_wholesale": Decimal("24100"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 8,
    },
    {
        "sku": "PGO-05",
        "name": "Pelota de Gel Ovalada 6.5cm Verde 20lbs",
        "category_slug": "pelotas",
        "brand": "CanDo",
        "unit_cost": Decimal("19000"),
        "sale_price_retail": Decimal("26000"),
        "sale_price_wholesale": Decimal("22900"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 10,
    },
    {
        "sku": "SAR-01",
        "name": "Set De Agarre Redondo-Malla Pelota 10.5cm x 3 piezas",
        "category_slug": "pelotas",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("28000"),
        "sale_price_retail": Decimal("38300"),
        "sale_price_wholesale": Decimal("33800"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 6,
    },
    {
        "sku": "APB-01",
        "name": "Balancin 33cm Azul con Inflador",
        "category_slug": "pelotas",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("38000"),
        "sale_price_retail": Decimal("52000"),
        "sale_price_wholesale": Decimal("45800"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 5,
    },
    {
        "sku": "BBM-01",
        "name": "Balon Bousu con Manillas 58x24cm Azul",
        "category_slug": "pelotas",
        "brand": "Gymnic",
        "unit_cost": Decimal("95000"),
        "sale_price_retail": Decimal("130100"),
        "sale_price_wholesale": Decimal("114600"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 3,
    },
    # ======================================================================
    # AGUJAS (APS y acupuntura)
    # ======================================================================
    {
        "sku": "AGJ-01",
        "name": "Aguja Puncion Seca APS Regular 0.25x25 con guia Rojo c/100",
        "category_slug": "agujas",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("38000"),
        "sale_price_retail": Decimal("52000"),
        "sale_price_wholesale": Decimal("45800"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 15,
        "requires_expiration": True,
    },
    {
        "sku": "AGJ-02",
        "name": "Aguja Puncion Seca APS Regular 0.30x40 con guia Blanco c/100",
        "category_slug": "agujas",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("38000"),
        "sale_price_retail": Decimal("52000"),
        "sale_price_wholesale": Decimal("45800"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 15,
        "requires_expiration": True,
    },
    {
        "sku": "AGJ-03",
        "name": "Aguja Puncion Seca APS Regular 0.30x50 con guia Rosa c/100",
        "category_slug": "agujas",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("40000"),
        "sale_price_retail": Decimal("54800"),
        "sale_price_wholesale": Decimal("48300"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 12,
        "requires_expiration": True,
    },
    {
        "sku": "AGJ-04",
        "name": "Aguja Puncion Seca APS Regular 0.30x60 con guia Lila c/100",
        "category_slug": "agujas",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("40000"),
        "sale_price_retail": Decimal("54800"),
        "sale_price_wholesale": Decimal("48300"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 12,
        "requires_expiration": True,
    },
    {
        "sku": "AGJ-05",
        "name": "Aguja Puncion Seca APS Regular 0.30x75 con guia Negro c/100",
        "category_slug": "agujas",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("42000"),
        "sale_price_retail": Decimal("57500"),
        "sale_price_wholesale": Decimal("50700"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 10,
        "requires_expiration": True,
    },
    {
        "sku": "AGJ-06",
        "name": "Aguja Puncion Seca APS Regular 0.25x40 con guia Amarillo c/100",
        "category_slug": "agujas",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("38000"),
        "sale_price_retail": Decimal("52000"),
        "sale_price_wholesale": Decimal("45800"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 12,
        "requires_expiration": True,
    },
    {
        "sku": "AGJ-08",
        "name": "Aguja Puncion Seca APS Regular 0.30x30 con guia Naranja c/100",
        "category_slug": "agujas",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("38000"),
        "sale_price_retail": Decimal("52000"),
        "sale_price_wholesale": Decimal("45800"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 15,
        "requires_expiration": True,
    },
    {
        "sku": "AGJ-09",
        "name": "Aguja Puncion Seca APS 0.18x25 con tubo Superficial Rojo-Blanco c/100",
        "category_slug": "agujas",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("45000"),
        "sale_price_retail": Decimal("61600"),
        "sale_price_wholesale": Decimal("54300"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 12,
        "requires_expiration": True,
    },
    {
        "sku": "AGJ-11",
        "name": "Aguja AGP Premium mango plata 0.16x25 c/200 unid",
        "category_slug": "agujas",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("58000"),
        "sale_price_retail": Decimal("79400"),
        "sale_price_wholesale": Decimal("69900"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 10,
        "requires_expiration": True,
    },
    {
        "sku": "AGJ-13",
        "name": "Aguja Electroterapia 0.30x30 mm caja 200 unidades",
        "category_slug": "agujas",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("62000"),
        "sale_price_retail": Decimal("84900"),
        "sale_price_wholesale": Decimal("74800"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 8,
        "requires_expiration": True,
    },
    # ======================================================================
    # ACCESORIOS (hoja Accesorios del Excel)
    # ======================================================================
    {
        "sku": "DND-01",
        "name": "Dinamometro Digital Negro",
        "category_slug": "accesorios",
        "brand": "Baseline",
        "unit_cost": Decimal("185000"),
        "sale_price_retail": Decimal("253400"),
        "sale_price_wholesale": Decimal("223300"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 2,
    },
    {
        "sku": "LDE-01",
        "name": "Luz de Entrenamiento de Reaccion y Agilidad",
        "category_slug": "accesorios",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("280000"),
        "sale_price_retail": Decimal("383400"),
        "sale_price_wholesale": Decimal("337800"),
        "tax_rate_pct": Decimal("19.00"),
        "reorder_point": 2,
    },
    {
        "sku": "PEM-01",
        "name": "Thera Med Profesional Heating Pad Medium Estandar 30x38cm",
        "category_slug": "accesorios",
        "brand": "Thera Med",
        "unit_cost": Decimal("85000"),
        "sale_price_retail": Decimal("116400"),
        "sale_price_wholesale": Decimal("102600"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 4,
    },
    {
        "sku": "PEK-02",
        "name": "Thera Med Profesional Heating Pad King Estandar 30x60cm",
        "category_slug": "accesorios",
        "brand": "Thera Med",
        "unit_cost": Decimal("110000"),
        "sale_price_retail": Decimal("150700"),
        "sale_price_wholesale": Decimal("132800"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 3,
    },
    {
        "sku": "RDHA-01",
        "name": "Rueda de Hombro Ajustable Digital",
        "category_slug": "accesorios",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("145000"),
        "sale_price_retail": Decimal("198600"),
        "sale_price_wholesale": Decimal("175000"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 2,
    },
    {
        "sku": "AD-01",
        "name": "Adipometro Slim Guide Blanco",
        "category_slug": "accesorios",
        "brand": "Baseline",
        "unit_cost": Decimal("65000"),
        "sale_price_retail": Decimal("89000"),
        "sale_price_wholesale": Decimal("78500"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 3,
    },
    {
        "sku": "AD-02",
        "name": "Adipometro Slim Guide Negro",
        "category_slug": "accesorios",
        "brand": "Baseline",
        "unit_cost": Decimal("65000"),
        "sale_price_retail": Decimal("89000"),
        "sale_price_wholesale": Decimal("78500"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 3,
    },
    {
        "sku": "BPM-02",
        "name": "Barras Paralelas x 2 Mts",
        "category_slug": "accesorios",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("680000"),
        "sale_price_retail": Decimal("931100"),
        "sale_price_wholesale": Decimal("820600"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 1,
    },
    {
        "sku": "CE-01",
        "name": "Cojin de Equilibrio Minibalancines 16x9cm Verde",
        "category_slug": "accesorios",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("22000"),
        "sale_price_retail": Decimal("30100"),
        "sale_price_wholesale": Decimal("26500"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 8,
    },
    {
        "sku": "CE-03",
        "name": "Cojin de Equilibrio Minibalancines 16x9cm Rojo",
        "category_slug": "accesorios",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("22000"),
        "sale_price_retail": Decimal("30100"),
        "sale_price_wholesale": Decimal("26500"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 8,
    },
    {
        "sku": "CE-04",
        "name": "Cojin de Equilibrio Minibalancines 16x9cm Azul",
        "category_slug": "accesorios",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("22000"),
        "sale_price_retail": Decimal("30100"),
        "sale_price_wholesale": Decimal("26500"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 8,
    },
    {
        "sku": "CE-05",
        "name": "Cojin de Equilibrio Minibalancines 16x9cm Naranja",
        "category_slug": "accesorios",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("22000"),
        "sale_price_retail": Decimal("30100"),
        "sale_price_wholesale": Decimal("26500"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 8,
    },
    {
        "sku": "CE-06",
        "name": "Cojin de Equilibrio Minibalancines 16x9cm Amarillo",
        "category_slug": "accesorios",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("22000"),
        "sale_price_retail": Decimal("30100"),
        "sale_price_wholesale": Decimal("26500"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 8,
    },
    {
        "sku": "CF-02",
        "name": "Compresa Fria Vinilo Cervical Relief Pak 15x58cm",
        "category_slug": "accesorios",
        "brand": "Relief Pak",
        "unit_cost": Decimal("28000"),
        "sale_price_retail": Decimal("38300"),
        "sale_price_wholesale": Decimal("33800"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 6,
    },
    {
        "sku": "CFCG-01",
        "name": "Compresa Fria/Caliente Gel Lite Mediana Relief Pak 12.5x25cm",
        "category_slug": "accesorios",
        "brand": "Relief Pak",
        "unit_cost": Decimal("22000"),
        "sale_price_retail": Decimal("30100"),
        "sale_price_wholesale": Decimal("26500"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 8,
    },
    {
        "sku": "CMA-02",
        "name": "Correa de Estiramiento Elastica",
        "category_slug": "accesorios",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("18000"),
        "sale_price_retail": Decimal("24600"),
        "sale_price_wholesale": Decimal("21700"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 10,
    },
    {
        "sku": "CMA-03",
        "name": "Correa de Estiramiento Fija con Soporte para Pie",
        "category_slug": "accesorios",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("22000"),
        "sale_price_retail": Decimal("30100"),
        "sale_price_wholesale": Decimal("26500"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 8,
    },
    {
        "sku": "CTE-01",
        "name": "Cajon Tipo Escalera",
        "category_slug": "accesorios",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("185000"),
        "sale_price_retail": Decimal("253400"),
        "sale_price_wholesale": Decimal("223300"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 1,
    },
    {
        "sku": "ECR-01",
        "name": "Escalera Con Rampa",
        "category_slug": "accesorios",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("220000"),
        "sale_price_retail": Decimal("301300"),
        "sale_price_wholesale": Decimal("265600"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 1,
    },
    {
        "sku": "EEM-01",
        "name": "Escalera de Entrenamiento de Marcha para Rehabilitacion",
        "category_slug": "accesorios",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("280000"),
        "sale_price_retail": Decimal("383400"),
        "sale_price_wholesale": Decimal("337800"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 1,
    },
    {
        "sku": "IMA-01",
        "name": "Instrumento de Medicion de Altura (Tallimetro)",
        "category_slug": "accesorios",
        "brand": "Baseline",
        "unit_cost": Decimal("95000"),
        "sale_price_retail": Decimal("130100"),
        "sale_price_wholesale": Decimal("114600"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 2,
    },
    {
        "sku": "IN-01",
        "name": "Inclinometro de Burbuja Baseline",
        "category_slug": "accesorios",
        "brand": "Baseline",
        "unit_cost": Decimal("45000"),
        "sale_price_retail": Decimal("61600"),
        "sale_price_wholesale": Decimal("54300"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 3,
    },
    {
        "sku": "MAC-01",
        "name": "Modelo Anatomico Columna Vertebral",
        "category_slug": "accesorios",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("185000"),
        "sale_price_retail": Decimal("253400"),
        "sale_price_wholesale": Decimal("223300"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 1,
    },
    {
        "sku": "MAP-02",
        "name": "Modelo Anatomico de Pelvis",
        "category_slug": "accesorios",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("145000"),
        "sale_price_retail": Decimal("198600"),
        "sale_price_wholesale": Decimal("175000"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 1,
    },
    {
        "sku": "MN-01",
        "name": "Mancuernas de Neopreno 1 Kg",
        "category_slug": "accesorios",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("18000"),
        "sale_price_retail": Decimal("24600"),
        "sale_price_wholesale": Decimal("21700"),
        "tax_rate_pct": Decimal("19.00"),
        "reorder_point": 10,
    },
    {
        "sku": "MN-02",
        "name": "Mancuernas de Neopreno 2 Kg",
        "category_slug": "accesorios",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("25000"),
        "sale_price_retail": Decimal("34200"),
        "sale_price_wholesale": Decimal("30200"),
        "tax_rate_pct": Decimal("19.00"),
        "reorder_point": 8,
    },
    {
        "sku": "MN-03",
        "name": "Mancuernas de Neopreno 3 Kg",
        "category_slug": "accesorios",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("32000"),
        "sale_price_retail": Decimal("43800"),
        "sale_price_wholesale": Decimal("38600"),
        "tax_rate_pct": Decimal("19.00"),
        "reorder_point": 6,
    },
    # EC-01b (codigo invalido) renombrado a ECB-1
    {
        "sku": "ECB-1",
        "name": "Pesas de Tobillo x 2 unid Negro/Azul 3 Kg",
        "category_slug": "accesorios",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("35000"),
        "sale_price_retail": Decimal("47900"),
        "sale_price_wholesale": Decimal("42200"),
        "tax_rate_pct": Decimal("19.00"),
        "reorder_point": 6,
    },
    {
        "sku": "SF-01",
        "name": "Set Fitness x 5 piezas",
        "category_slug": "accesorios",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("65000"),
        "sale_price_retail": Decimal("89000"),
        "sale_price_wholesale": Decimal("78500"),
        "tax_rate_pct": Decimal("19.00"),
        "reorder_point": 3,
    },
    {
        "sku": "SG-01",
        "name": "Set de Goniometros x 6 Piezas",
        "category_slug": "accesorios",
        "brand": "Baseline",
        "unit_cost": Decimal("55000"),
        "sale_price_retail": Decimal("75300"),
        "sale_price_wholesale": Decimal("66400"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 3,
    },
    {
        "sku": "TCT-01",
        "name": "Tijera de Trauma Corta Todo 15.5cm",
        "category_slug": "accesorios",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("18000"),
        "sale_price_retail": Decimal("24600"),
        "sale_price_wholesale": Decimal("21700"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 8,
    },
    {
        "sku": "TCT-02",
        "name": "Tijera de Trauma Corta Todo 18.5cm",
        "category_slug": "accesorios",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("20000"),
        "sale_price_retail": Decimal("27400"),
        "sale_price_wholesale": Decimal("24100"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 8,
    },
    # ======================================================================
    # CAMILLAS
    # ======================================================================
    {
        "sku": "CM-01",
        "name": "Camilla Para Masaje WT231A Negra",
        "category_slug": "camillas",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("480000"),
        "sale_price_retail": Decimal("657500"),
        "sale_price_wholesale": Decimal("579500"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 1,
        "weight_grams": 14000,
    },
    {
        "sku": "CMQ-01",
        "name": "Camilla Quiropractica Portatil ARENA-180",
        "category_slug": "camillas",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("650000"),
        "sale_price_retail": Decimal("890000"),
        "sale_price_wholesale": Decimal("784500"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 1,
        "weight_grams": 18000,
    },
    # ======================================================================
    # PEDALES
    # ======================================================================
    {
        "sku": "PD-03",
        "name": "Pedal Ejercitador ICM Therapy",
        "category_slug": "pedales",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("68000"),
        "sale_price_retail": Decimal("93100"),
        "sale_price_wholesale": Decimal("82000"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 5,
    },
    {
        "sku": "PD-04",
        "name": "Pedal de Estiramiento Sencillo (Patin) Negro",
        "category_slug": "pedales",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("35000"),
        "sale_price_retail": Decimal("47900"),
        "sale_price_wholesale": Decimal("42200"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 6,
    },
    {
        "sku": "PD-05",
        "name": "Pedal de Estiramiento Sencillo (Patin) Azul",
        "category_slug": "pedales",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("35000"),
        "sale_price_retail": Decimal("47900"),
        "sale_price_wholesale": Decimal("42200"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 6,
    },
    {
        "sku": "PD-06",
        "name": "Pedal Ejercitador Electrico ICMTHERAPY",
        "category_slug": "pedales",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("180000"),
        "sale_price_retail": Decimal("246500"),
        "sale_price_wholesale": Decimal("217300"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 2,
    },
    # ======================================================================
    # SUELO PELVICO
    # ======================================================================
    {
        "sku": "TC-05",
        "name": "Perfect PFE For Men Pelvic Floor Exerciser Massage Kit",
        "category_slug": "suelo-pelvico",
        "brand": "TensCare",
        "unit_cost": Decimal("280000"),
        "sale_price_retail": Decimal("383400"),
        "sale_price_wholesale": Decimal("337800"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 2,
    },
    {
        "sku": "TC-06",
        "name": "Sure PRO Pelvic Floor Exerciser",
        "category_slug": "suelo-pelvico",
        "brand": "TensCare",
        "unit_cost": Decimal("320000"),
        "sale_price_retail": Decimal("438400"),
        "sale_price_wholesale": Decimal("386400"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 2,
    },
    {
        "sku": "TC-08",
        "name": "Unicare Pelvic Floor Exerciser",
        "category_slug": "suelo-pelvico",
        "brand": "TensCare",
        "unit_cost": Decimal("350000"),
        "sale_price_retail": Decimal("479500"),
        "sale_price_wholesale": Decimal("422500"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 2,
    },
    {
        "sku": "TC-10",
        "name": "Mynd Estimulador Suelo Pelvico TensCare",
        "category_slug": "suelo-pelvico",
        "brand": "TensCare",
        "unit_cost": Decimal("480000"),
        "sale_price_retail": Decimal("657500"),
        "sale_price_wholesale": Decimal("579500"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 1,
    },
    {
        "sku": "TC-11",
        "name": "Mynd Gel Pads Replacement Pads TensCare",
        "category_slug": "suelo-pelvico",
        "brand": "TensCare",
        "unit_cost": Decimal("38000"),
        "sale_price_retail": Decimal("52000"),
        "sale_price_wholesale": Decimal("45800"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 8,
        "requires_expiration": True,
    },
    {
        "sku": "TC-12",
        "name": "Cables L-CPT TensCare Blanco",
        "category_slug": "suelo-pelvico",
        "brand": "TensCare",
        "unit_cost": Decimal("28000"),
        "sale_price_retail": Decimal("38300"),
        "sale_price_wholesale": Decimal("33800"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 8,
    },
    {
        "sku": "TC-13",
        "name": "Cables L-ST2 TensCare Gris",
        "category_slug": "suelo-pelvico",
        "brand": "TensCare",
        "unit_cost": Decimal("28000"),
        "sale_price_retail": Decimal("38300"),
        "sale_price_wholesale": Decimal("33800"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 8,
    },
    {
        "sku": "TC-18",
        "name": "Estimulador Neuromuscular Biofeedback KM530",
        "category_slug": "suelo-pelvico",
        "brand": "KM Medical",
        "unit_cost": Decimal("580000"),
        "sale_price_retail": Decimal("794200"),
        "sale_price_wholesale": Decimal("699700"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 1,
    },
    {
        "sku": "TC-19",
        "name": "Estimulador Neuromuscular Biofeedback KM531",
        "category_slug": "suelo-pelvico",
        "brand": "KM Medical",
        "unit_cost": Decimal("680000"),
        "sale_price_retail": Decimal("931100"),
        "sale_price_wholesale": Decimal("820600"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 1,
    },
    # ======================================================================
    # TERAPIAS DE MANO
    # ======================================================================
    # --- Entrenadores de dedos roboticos ---
    {
        "sku": "ED-02",
        "name": "Entrenador de Dedos Sencillo Mano Robot Talla M Derecha",
        "category_slug": "terapias-de-mano",
        "brand": "Mano Robot",
        "unit_cost": Decimal("185000"),
        "sale_price_retail": Decimal("253400"),
        "sale_price_wholesale": Decimal("223300"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 2,
    },
    {
        "sku": "ED-03",
        "name": "Entrenador de Dedos Sencillo Mano Robot Talla M Izquierda",
        "category_slug": "terapias-de-mano",
        "brand": "Mano Robot",
        "unit_cost": Decimal("185000"),
        "sale_price_retail": Decimal("253400"),
        "sale_price_wholesale": Decimal("223300"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 2,
    },
    {
        "sku": "ED-04",
        "name": "Entrenador de Dedos Sencillo Mano Robot Talla L Derecha",
        "category_slug": "terapias-de-mano",
        "brand": "Mano Robot",
        "unit_cost": Decimal("195000"),
        "sale_price_retail": Decimal("267100"),
        "sale_price_wholesale": Decimal("235300"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 2,
    },
    {
        "sku": "ED-05",
        "name": "Entrenador de Dedos Sencillo Mano Robot Talla L Izquierda",
        "category_slug": "terapias-de-mano",
        "brand": "Mano Robot",
        "unit_cost": Decimal("195000"),
        "sale_price_retail": Decimal("267100"),
        "sale_price_wholesale": Decimal("235300"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 2,
    },
    # --- Digiflex CanDo ---
    {
        "sku": "DGC-01",
        "name": "Digiflex Cando Amarillo",
        "category_slug": "terapias-de-mano",
        "brand": "CanDo",
        "unit_cost": Decimal("32000"),
        "sale_price_retail": Decimal("43800"),
        "sale_price_wholesale": Decimal("38600"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 8,
    },
    {
        "sku": "DGC-02",
        "name": "Digiflex Cando Azul",
        "category_slug": "terapias-de-mano",
        "brand": "CanDo",
        "unit_cost": Decimal("32000"),
        "sale_price_retail": Decimal("43800"),
        "sale_price_wholesale": Decimal("38600"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 8,
    },
    {
        "sku": "DGC-03",
        "name": "Digiflex Cando Rojo",
        "category_slug": "terapias-de-mano",
        "brand": "CanDo",
        "unit_cost": Decimal("35000"),
        "sale_price_retail": Decimal("47900"),
        "sale_price_wholesale": Decimal("42200"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 8,
    },
    {
        "sku": "DGC-04",
        "name": "Digiflex Cando Verde",
        "category_slug": "terapias-de-mano",
        "brand": "CanDo",
        "unit_cost": Decimal("38000"),
        "sale_price_retail": Decimal("52000"),
        "sale_price_wholesale": Decimal("45800"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 6,
    },
    {
        "sku": "DGC-05",
        "name": "Digiflex Cando Negro",
        "category_slug": "terapias-de-mano",
        "brand": "CanDo",
        "unit_cost": Decimal("42000"),
        "sale_price_retail": Decimal("57500"),
        "sale_price_wholesale": Decimal("50700"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 5,
    },
    # --- Digiflex Lite ---
    {
        "sku": "DGL-01",
        "name": "Digiflex Lite Amarillo",
        "category_slug": "terapias-de-mano",
        "brand": "CanDo",
        "unit_cost": Decimal("28000"),
        "sale_price_retail": Decimal("38300"),
        "sale_price_wholesale": Decimal("33800"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 8,
    },
    {
        "sku": "DGL-02",
        "name": "Digiflex Lite Azul",
        "category_slug": "terapias-de-mano",
        "brand": "CanDo",
        "unit_cost": Decimal("28000"),
        "sale_price_retail": Decimal("38300"),
        "sale_price_wholesale": Decimal("33800"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 8,
    },
    {
        "sku": "DGL-03",
        "name": "Digiflex Lite Rojo",
        "category_slug": "terapias-de-mano",
        "brand": "CanDo",
        "unit_cost": Decimal("30000"),
        "sale_price_retail": Decimal("41100"),
        "sale_price_wholesale": Decimal("36200"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 8,
    },
    {
        "sku": "DGL-04",
        "name": "Digiflex Lite Verde",
        "category_slug": "terapias-de-mano",
        "brand": "CanDo",
        "unit_cost": Decimal("32000"),
        "sale_price_retail": Decimal("43800"),
        "sale_price_wholesale": Decimal("38600"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 6,
    },
    {
        "sku": "DGL-05",
        "name": "Digiflex Lite Negro",
        "category_slug": "terapias-de-mano",
        "brand": "CanDo",
        "unit_cost": Decimal("35000"),
        "sale_price_retail": Decimal("47900"),
        "sale_price_wholesale": Decimal("42200"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 5,
    },
    # --- Fortalecedores ---
    {
        "sku": "EC-01",
        "name": "Fortalecedor de Mano y Muneca Sencillo Hand Grip",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("18000"),
        "sale_price_retail": Decimal("24600"),
        "sale_price_wholesale": Decimal("21700"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 12,
    },
    {
        "sku": "EDAA-01",
        "name": "Entrenador de Agarre Ajustable Negro-Naranja",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("28000"),
        "sale_price_retail": Decimal("38300"),
        "sale_price_wholesale": Decimal("33800"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 6,
    },
    {
        "sku": "EDD-01",
        "name": "Escalerilla De Dedos",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("22000"),
        "sale_price_retail": Decimal("30100"),
        "sale_price_wholesale": Decimal("26500"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 6,
    },
    {
        "sku": "EDH-01",
        "name": "Escalera De Hombro",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("38000"),
        "sale_price_retail": Decimal("52000"),
        "sale_price_wholesale": Decimal("45800"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 4,
    },
    {
        "sku": "EDM-01",
        "name": "Ejercitador De Mano En Malla Rosado 20 Lb",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("12000"),
        "sale_price_retail": Decimal("16400"),
        "sale_price_wholesale": Decimal("14500"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 12,
    },
    {
        "sku": "EDM-02",
        "name": "Ejercitador De Mano En Malla Azul 40 Lb",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("12000"),
        "sale_price_retail": Decimal("16400"),
        "sale_price_wholesale": Decimal("14500"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 12,
    },
    {
        "sku": "EDM-03",
        "name": "Ejercitador De Mano En Malla Gris 60 Lb",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("13000"),
        "sale_price_retail": Decimal("17800"),
        "sale_price_wholesale": Decimal("15700"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 10,
    },
    {
        "sku": "EDS-01",
        "name": "Set Ejercitador de Dedos en Silicona x 3",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("22000"),
        "sale_price_retail": Decimal("30100"),
        "sale_price_wholesale": Decimal("26500"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 8,
    },
    # --- Donas fortalecedoras ---
    {
        "sku": "FA-01",
        "name": "Dona Fortalecedor De Mano 7cm Amarilla 20 Lbs",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("8000"),
        "sale_price_retail": Decimal("10900"),
        "sale_price_wholesale": Decimal("9600"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 15,
    },
    {
        "sku": "FA-02",
        "name": "Dona Fortalecedor De Mano 7cm Verde 30 Lbs",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("8000"),
        "sale_price_retail": Decimal("10900"),
        "sale_price_wholesale": Decimal("9600"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 15,
    },
    {
        "sku": "FA-03",
        "name": "Dona Fortalecedor De Mano 7cm Azul 40 Lbs",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("9000"),
        "sale_price_retail": Decimal("12300"),
        "sale_price_wholesale": Decimal("10900"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 12,
    },
    {
        "sku": "FA-04",
        "name": "Dona Fortalecedor De Mano 7cm Naranja 50 Lbs",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("9000"),
        "sale_price_retail": Decimal("12300"),
        "sale_price_wholesale": Decimal("10900"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 10,
    },
    {
        "sku": "FA-05",
        "name": "Dona Fortalecedor De Mano 7cm Negro 60 Lbs",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("10000"),
        "sale_price_retail": Decimal("13700"),
        "sale_price_wholesale": Decimal("12100"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 10,
    },
    # --- Flexbar ---
    {
        "sku": "FL-03",
        "name": "Flexbar Rojo ICMTHERAPY",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("38000"),
        "sale_price_retail": Decimal("52000"),
        "sale_price_wholesale": Decimal("45800"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 5,
    },
    {
        "sku": "FL-04",
        "name": "Flexbar Verde ICMTHERAPY",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("42000"),
        "sale_price_retail": Decimal("57500"),
        "sale_price_wholesale": Decimal("50700"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 4,
    },
    {
        "sku": "FL-05",
        "name": "Flexbar Azul CanDo",
        "category_slug": "terapias-de-mano",
        "brand": "CanDo",
        "unit_cost": Decimal("45000"),
        "sale_price_retail": Decimal("61600"),
        "sale_price_wholesale": Decimal("54300"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 4,
    },
    # S/C renombrados: FL-1, FL-2
    {
        "sku": "FL-1",
        "name": "Flexbar Amarillo ICMTHERAPY",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("32000"),
        "sale_price_retail": Decimal("43800"),
        "sale_price_wholesale": Decimal("38600"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 6,
    },
    {
        "sku": "FL-2",
        "name": "Flexbar Azul ICMTHERAPY",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("45000"),
        "sale_price_retail": Decimal("61600"),
        "sale_price_wholesale": Decimal("54300"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 4,
    },
    # --- Plastilinas CanDo (presentaciones) ---
    {
        "sku": "PB-04",
        "name": "Plastilina Cando x 4.5 lbs Verde",
        "category_slug": "terapias-de-mano",
        "brand": "CanDo",
        "unit_cost": Decimal("52000"),
        "sale_price_retail": Decimal("71200"),
        "sale_price_wholesale": Decimal("62800"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 5,
    },
    {
        "sku": "PB-06",
        "name": "Plastilina Cando x 4.5 lbs Negra",
        "category_slug": "terapias-de-mano",
        "brand": "CanDo",
        "unit_cost": Decimal("58000"),
        "sale_price_retail": Decimal("79400"),
        "sale_price_wholesale": Decimal("69900"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 4,
    },
    # --- Plastilinas ICM Therapy 5 lbs ---
    {
        "sku": "PB-07",
        "name": "Plastilina ICMTHERAPY x 5 libras Amarilla",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("42000"),
        "sale_price_retail": Decimal("57500"),
        "sale_price_wholesale": Decimal("50700"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 6,
    },
    {
        "sku": "PB-08",
        "name": "Plastilina ICMTHERAPY x 5 libras Roja",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("42000"),
        "sale_price_retail": Decimal("57500"),
        "sale_price_wholesale": Decimal("50700"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 6,
    },
    {
        "sku": "PB-09",
        "name": "Plastilina ICMTHERAPY x 5 libras Verde",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("45000"),
        "sale_price_retail": Decimal("61600"),
        "sale_price_wholesale": Decimal("54300"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 5,
    },
    {
        "sku": "PB-10",
        "name": "Plastilina ICM Therapy x 5 libras Azul",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("48000"),
        "sale_price_retail": Decimal("65700"),
        "sale_price_wholesale": Decimal("57900"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 4,
    },
    {
        "sku": "PB-11",
        "name": "Plastilina ICM Therapy x 5 libras Negra",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("52000"),
        "sale_price_retail": Decimal("71200"),
        "sale_price_wholesale": Decimal("62800"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 3,
    },
    # --- Plastilinas libra ---
    {
        "sku": "PL-06",
        "name": "Plastilina Cando x libra Negra",
        "category_slug": "terapias-de-mano",
        "brand": "CanDo",
        "unit_cost": Decimal("14000"),
        "sale_price_retail": Decimal("19200"),
        "sale_price_wholesale": Decimal("16900"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 10,
    },
    {
        "sku": "PL-07",
        "name": "Plastilina ICM Therapy x libra Amarilla",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("10000"),
        "sale_price_retail": Decimal("13700"),
        "sale_price_wholesale": Decimal("12100"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 12,
    },
    {
        "sku": "PL-08",
        "name": "Plastilina ICM Therapy x libra Roja",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("10000"),
        "sale_price_retail": Decimal("13700"),
        "sale_price_wholesale": Decimal("12100"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 12,
    },
    {
        "sku": "PL-09",
        "name": "Plastilina ICM Therapy x libra Azul",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("11000"),
        "sale_price_retail": Decimal("15100"),
        "sale_price_wholesale": Decimal("13300"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 10,
    },
    {
        "sku": "PL-10",
        "name": "Plastilina ICM Therapy x libra Verde",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("11000"),
        "sale_price_retail": Decimal("15100"),
        "sale_price_wholesale": Decimal("13300"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 10,
    },
    {
        "sku": "PL-11",
        "name": "Plastilina ICM Therapy x libra Negra",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("12000"),
        "sale_price_retail": Decimal("16400"),
        "sale_price_wholesale": Decimal("14500"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 10,
    },
    # --- Plastilinas 2 oz ---
    {
        "sku": "PO-04",
        "name": "Plastilina Cando x 2 oz Verde",
        "category_slug": "terapias-de-mano",
        "brand": "CanDo",
        "unit_cost": Decimal("5500"),
        "sale_price_retail": Decimal("7500"),
        "sale_price_wholesale": Decimal("6600"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 20,
    },
    {
        "sku": "PO-06",
        "name": "Plastilina Cando x 2 oz Negra",
        "category_slug": "terapias-de-mano",
        "brand": "CanDo",
        "unit_cost": Decimal("5800"),
        "sale_price_retail": Decimal("7900"),
        "sale_price_wholesale": Decimal("6900"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 15,
    },
    {
        "sku": "PO-07",
        "name": "Plastilina ICM Therapy x 2 oz Amarilla",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("4500"),
        "sale_price_retail": Decimal("6200"),
        "sale_price_wholesale": Decimal("5400"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 25,
    },
    {
        "sku": "PO-08",
        "name": "Plastilina ICM Therapy x 2 oz Roja",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("4500"),
        "sale_price_retail": Decimal("6200"),
        "sale_price_wholesale": Decimal("5400"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 25,
    },
    {
        "sku": "PO-09",
        "name": "Plastilina ICM Therapy x 2 oz Verde",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("4800"),
        "sale_price_retail": Decimal("6600"),
        "sale_price_wholesale": Decimal("5800"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 25,
    },
    {
        "sku": "PO-10",
        "name": "Plastilina ICM Therapy x 2 oz Negra",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("5200"),
        "sale_price_retail": Decimal("7100"),
        "sale_price_wholesale": Decimal("6300"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 20,
    },
    {
        "sku": "PO-11",
        "name": "Plastilina ICM Therapy x 2 oz Azul",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("5000"),
        "sale_price_retail": Decimal("6800"),
        "sale_price_wholesale": Decimal("6000"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 20,
    },
    # --- Juegos didacticos ---
    {
        "sku": "JD-01",
        "name": "Juego Didactico Tablas de Aprendizaje de Vestir",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("38000"),
        "sale_price_retail": Decimal("52000"),
        "sale_price_wholesale": Decimal("45800"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 3,
    },
    {
        "sku": "JD-02",
        "name": "Juego Didactico de Enhebrado con Cordones",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("28000"),
        "sale_price_retail": Decimal("38300"),
        "sale_price_wholesale": Decimal("33800"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 3,
    },
    {
        "sku": "JD-03",
        "name": "Juego Didactico Tablero de Clavijas",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("45000"),
        "sale_price_retail": Decimal("61600"),
        "sale_price_wholesale": Decimal("54300"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 2,
    },
    {
        "sku": "JD-04",
        "name": "Juego Didactico Conteo de Animales",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("32000"),
        "sale_price_retail": Decimal("43800"),
        "sale_price_wholesale": Decimal("38600"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 3,
    },
    {
        "sku": "JD-05",
        "name": "Juego Didactico de Aros Magneticos",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("35000"),
        "sale_price_retail": Decimal("47900"),
        "sale_price_wholesale": Decimal("42200"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 3,
    },
    # --- Soportes y herramientas ---
    {
        "sku": "SEM-01",
        "name": "Soporte de Entrenamiento Para Dedos Amarilla con Sujetador",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("18000"),
        "sale_price_retail": Decimal("24600"),
        "sale_price_wholesale": Decimal("21700"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 6,
    },
    {
        "sku": "SEM-02",
        "name": "Soporte de Entrenamiento Para Dedos Blanca con Sujetador",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("18000"),
        "sale_price_retail": Decimal("24600"),
        "sale_price_wholesale": Decimal("21700"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 6,
    },
    {
        "sku": "HMA-01",
        "name": "Herramienta Manual Acero Sencilla Tipo Garra",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("55000"),
        "sale_price_retail": Decimal("75300"),
        "sale_price_wholesale": Decimal("66400"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 3,
    },
    {
        "sku": "HMA-02",
        "name": "Herramienta Manual Acero Sencilla Tipo S",
        "category_slug": "terapias-de-mano",
        "brand": "ICM Therapy",
        "unit_cost": Decimal("55000"),
        "sale_price_retail": Decimal("75300"),
        "sale_price_wholesale": Decimal("66400"),
        "tax_rate_pct": Decimal("0.00"),
        "reorder_point": 3,
    },
]

# ---------------------------------------------------------------------------
# Combos de productos (RF-003) — usando SKUs reales del catalogo
# ---------------------------------------------------------------------------
COMBOS: list[dict[str, Any]] = [
    {
        "sku": "KIT-1",
        "name": "Kit TENS Basico (TENS + Electrodos + Gel)",
        "items": [("T-01", 1), ("EL-01", 1), ("GL-03", 1)],
        "price_strategy": "fixed",
        "fixed_price_retail": Decimal("480000"),
        "fixed_price_wholesale": Decimal("420000"),
    },
    {
        "sku": "KAPS-1",
        "name": "Kit Puncion Seca Basico (2 calibres APS)",
        "items": [("AGJ-01", 1), ("AGJ-02", 1)],
        "price_strategy": "derived",
    },
    {
        "sku": "KBND-1",
        "name": "Pack Bandas Precortadas 5 Colores TheraBand",
        "items": [("BP-08", 1), ("BP-09", 1), ("BP-10", 1), ("BP-11", 1), ("BP-12", 1)],
        "price_strategy": "fixed",
        "fixed_price_retail": Decimal("60000"),
        "fixed_price_wholesale": Decimal("52000"),
    },
]

# ---------------------------------------------------------------------------
# Cantidades de stock por categoria para las OC del seed
# ---------------------------------------------------------------------------
CATEGORY_QTY: dict[str, int] = {
    "electroterapia": 6,
    "masajeadores": 8,
    "bandas": 40,
    "cintas": 50,
    "pelotas": 15,
    "agujas": 60,
    "accesorios": 20,
    "camillas": 2,
    "pedales": 8,
    "suelo-pelvico": 5,
    "terapias-de-mano": 15,
}
DEFAULT_QTY = 6

# ---------------------------------------------------------------------------
# Proveedores
# ---------------------------------------------------------------------------
SUPPLIERS: list[dict[str, Any]] = [
    {
        "nombre_comercial": "ICM Distribuidora Principal SAS",
        "razon_social": "ICM Distribuidora Principal SAS",
        "nit": "900111222-3",
        "pais": "Colombia",
        "correo": "ventas@icmdistribuidora.co",
        "telefono": "+57 1 3001112",
        "ciudad": "Bogota",
        "direccion": "Cra 7 No 32-15 Of 301, Bogota",
        "observaciones": "Proveedor principal electroterapia y masajeadores.",
    },
    {
        "nombre_comercial": "Terapias Medicas de Colombia Ltda",
        "razon_social": "Terapias Medicas de Colombia Ltda.",
        "nit": "830222333-4",
        "pais": "Colombia",
        "correo": "pedidos@terapiasmedicas.co",
        "telefono": "+57 1 4002223",
        "ciudad": "Bogota",
        "direccion": "Av. El Dorado 68B-61, Bogota",
        "observaciones": "Bandas, cintas y pelotas terapeuticas.",
    },
    {
        "nombre_comercial": "Distribuidora Agujas y Accesorios SAS",
        "razon_social": "Distribuidora Agujas y Accesorios SAS",
        "nit": "805333444-5",
        "pais": "Colombia",
        "correo": "compras@agujasyneedles.co",
        "telefono": "+57 2 3003334",
        "ciudad": "Cali",
        "direccion": "Calle 5 No 38-25, Cali",
        "observaciones": "Agujas de puncion seca y accesorios de fisioterapia.",
    },
    {
        "nombre_comercial": "Equimed Colombia SAS",
        "razon_social": "Equimed Colombia SAS",
        "nit": "860444555-6",
        "pais": "Colombia",
        "correo": "logistica@equimed.co",
        "telefono": "+57 4 2004445",
        "ciudad": "Medellin",
        "direccion": "Cra 43A 4-22, El Poblado, Medellin",
        "observaciones": "Camillas, pedales, suelo pelvico y terapias de mano.",
    },
    {
        "nombre_comercial": "MedRehab Importaciones Ltda.",
        "razon_social": "MedRehab Importaciones Ltda.",
        "nit": "900555666-7",
        "pais": "Colombia",
        "correo": "import@medrehab.com.co",
        "telefono": "+57 5 1005556",
        "ciudad": "Barranquilla",
        "direccion": "Calle 72 No 57-30, Barranquilla",
        "observaciones": "Importador multimarca para bodega norte.",
    },
]

# ---------------------------------------------------------------------------
# Ubicaciones adicionales
# ---------------------------------------------------------------------------
EXTRA_LOCATIONS: list[dict[str, Any]] = [
    {
        "code": "bodega-norte",
        "name": "Bodega Norte",
        "description": "Almacenamiento secundario, sector norte.",
        "is_retail": False,
    },
    {
        "code": "vitrina-2",
        "name": "Vitrina 2",
        "description": "Punto de exhibicion y venta secundario.",
        "is_retail": True,
        "max_capacity": 100,
    },
]

# ---------------------------------------------------------------------------
# Clientes para ventas al por mayor (SALIDA_VENTA_MAYOR)
# ---------------------------------------------------------------------------
CUSTOMERS: list[dict[str, Any]] = [
    {
        "customer_name": "Clinica Rehabilita SAS",
        "customer_email": "compras@rehabilita.co",
        "customer_phone": "+57 1 5678901",
        "customer_address": "Cra 15 No 93-75, Bogota",
        "privacy_notice_acknowledged": True,
    },
    {
        "customer_name": "Fisioterapia Integral del Caribe",
        "customer_email": "admin@fisiointegralcaribe.com",
        "customer_phone": "+57 5 3456789",
        "customer_address": "Calle 72 No 57-30, Barranquilla",
        "privacy_notice_acknowledged": True,
    },
    {
        "customer_name": "Centro Medico San Lucas",
        "customer_email": "logistica@sanlucas.co",
        "customer_phone": "+57 2 8901234",
        "customer_address": "Av 2N No 24-39, Cali",
        "privacy_notice_acknowledged": True,
    },
    {
        "customer_name": "IPS Terapia y Salud Medellin",
        "customer_email": "gerencia@terapiaysalud.co",
        "customer_phone": "+57 4 7654321",
        "customer_address": "Cra 65 No 45-20, Medellin",
        "privacy_notice_acknowledged": True,
    },
    {
        "customer_name": "Hospital Regional del Norte",
        "customer_email": "suministros@hospitalregional.gov.co",
        "customer_phone": "+57 7 3219876",
        "customer_address": "Calle 35 No 22-18, Bucaramanga",
        "privacy_notice_acknowledged": True,
    },
]
