from django.urls import path

from apps.inventory.views import (
    InventoryFullListView,
    LocationDetailView,
    LocationListCreateView,
    LocationRestoreView,
    LocationStateTransitionView,
    ProductSearchView,
    ReconstructStockView,
    StockByLocationView,
    StockByProductView,
    StockThresholdView,
    StorageTemplateDetailView,
    StorageTemplateDisableView,
    StorageTemplateEnableView,
    StorageTemplateListCreateView,
    StorageTemplateRestoreView,
    StorageTypeDetailView,
    StorageTypeDisableView,
    StorageTypeEnableView,
    StorageTypeListCreateView,
    StorageTypeRestoreView,
)

urlpatterns = [
    path("", InventoryFullListView.as_view(), name="inventory-full"),
    path(
        "storage-types/",
        StorageTypeListCreateView.as_view(),
        name="inventory-storage-types",
    ),
    path(
        "storage-types/<uuid:pk>/",
        StorageTypeDetailView.as_view(),
        name="inventory-storage-type-detail",
    ),
    path(
        "storage-types/<uuid:pk>/restore/",
        StorageTypeRestoreView.as_view(),
        name="inventory-storage-type-restore",
    ),
    path(
        "storage-types/<uuid:pk>/disable/",
        StorageTypeDisableView.as_view(),
        name="inventory-storage-type-disable",
    ),
    path(
        "storage-types/<uuid:pk>/enable/",
        StorageTypeEnableView.as_view(),
        name="inventory-storage-type-enable",
    ),
    path(
        "storage-templates/",
        StorageTemplateListCreateView.as_view(),
        name="inventory-storage-templates",
    ),
    path(
        "storage-templates/<uuid:pk>/",
        StorageTemplateDetailView.as_view(),
        name="inventory-storage-template-detail",
    ),
    path(
        "storage-templates/<uuid:pk>/restore/",
        StorageTemplateRestoreView.as_view(),
        name="inventory-storage-template-restore",
    ),
    path(
        "storage-templates/<uuid:pk>/disable/",
        StorageTemplateDisableView.as_view(),
        name="inventory-storage-template-disable",
    ),
    path(
        "storage-templates/<uuid:pk>/enable/",
        StorageTemplateEnableView.as_view(),
        name="inventory-storage-template-enable",
    ),
    path("locations/", LocationListCreateView.as_view(), name="inventory-locations"),
    path(
        "locations/<uuid:pk>/",
        LocationDetailView.as_view(),
        name="inventory-location-detail",
    ),
    path(
        "locations/<uuid:pk>/restore/",
        LocationRestoreView.as_view(),
        name="inventory-location-restore",
    ),
    path(
        "locations/<uuid:pk>/state-transitions/",
        LocationStateTransitionView.as_view(),
        name="inventory-location-state-transitions",
    ),
    path("reconstruct/", ReconstructStockView.as_view(), name="inventory-reconstruct"),
    path(
        "products/<uuid:product_id>/stock/",
        StockByProductView.as_view(),
        name="inventory-product-stock",
    ),
    path(
        "stock/product/<uuid:product_id>/",
        StockByProductView.as_view(),
        name="inventory-stock-product",
    ),
    path(
        "stock/location/<uuid:location_id>/",
        StockByLocationView.as_view(),
        name="inventory-stock-location",
    ),
    path("search/", ProductSearchView.as_view(), name="inventory-search"),
    path(
        "stock/<uuid:pk>/threshold/",
        StockThresholdView.as_view(),
        name="inventory-stock-threshold",
    ),
]
