# Generated by Django 5.2.4 on 2026-05-04 23:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha y hora de creación (UTC)."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha y hora de última modificación (UTC).",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("VITRINA", "Vitrina"),
                            ("BODEGA_1", "Bodega 1"),
                            ("BODEGA_2", "Bodega 2"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "is_retail",
                    models.BooleanField(
                        default=False,
                        help_text="BR-11: True solo para Vitrina (punto minorista).",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Ubicación",
                "verbose_name_plural": "Ubicaciones",
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="StockByLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha y hora de creación (UTC)."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha y hora de última modificación (UTC).",
                    ),
                ),
                (
                    "current_stock",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="BR-11: stock derivado; debe reconstruirse desde el ledger.",
                    ),
                ),
                (
                    "last_movement_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Último movimiento que alteró este registro (auditoría rápida).",
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_items",
                        to="inventory.location",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_by_location",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock por Ubicación",
                "verbose_name_plural": "Stock por ubicación",
                "indexes": [
                    models.Index(
                        fields=["product", "location"],
                        name="inventory_s_product_2b77c7_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "location"),
                        name="uniq_product_location_stock",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("current_stock__gte", 0)),
                        name="stock_non_negative",
                    ),
                ],
            },
        ),
    ]
