# Generated by ChatGPT Codex on 2026-05-30

from django.db import migrations, models
import django.db.models.deletion
import uuid


def seed_storage_types_and_backfill_locations(apps, schema_editor):
    StorageType = apps.get_model("inventory", "StorageType")
    Location = apps.get_model("inventory", "Location")

    defaults = [
        {
            "code": "bodega",
            "name": "Bodega",
            "category": "warehouse",
            "description": "Almacenamiento general de bodega.",
            "default_is_retail": False,
            "is_system": True,
            "sort_order": 10,
        },
        {
            "code": "vitrina",
            "name": "Vitrina",
            "category": "retail",
            "description": "Punto de exhibición y venta minorista.",
            "default_is_retail": True,
            "is_system": True,
            "sort_order": 20,
        },
        {
            "code": "cuarto-frio",
            "name": "Cuarto frío",
            "category": "cold_chain",
            "description": "Almacenamiento refrigerado controlado.",
            "default_is_retail": False,
            "is_system": True,
            "sort_order": 30,
        },
        {
            "code": "nevera",
            "name": "Nevera",
            "category": "cold_chain",
            "description": "Almacenamiento en nevera/refrigeración ligera.",
            "default_is_retail": False,
            "is_system": True,
            "sort_order": 40,
        },
        {
            "code": "espacio-personalizado",
            "name": "Espacio personalizado",
            "category": "custom",
            "description": "Espacio configurable por operación.",
            "default_is_retail": False,
            "is_system": True,
            "sort_order": 50,
        },
    ]

    created = {}
    for item in defaults:
        st, _ = StorageType.objects.get_or_create(
            code=item["code"],
            defaults={
                "name": item["name"],
                "category": item["category"],
                "description": item["description"],
                "capabilities": {},
                "default_is_retail": item["default_is_retail"],
                "is_system": item["is_system"],
                "is_active": True,
                "sort_order": item["sort_order"],
            },
        )
        created[item["code"]] = st

    default_custom = created["espacio-personalizado"]
    st_bodega = created["bodega"]
    st_vitrina = created["vitrina"]
    st_frio = created["cuarto-frio"]
    st_nevera = created["nevera"]

    for loc in Location.objects.all():
        lname = (loc.name or "").lower().strip()
        if loc.is_retail:
            loc.storage_type = st_vitrina
        elif "nevera" in lname:
            loc.storage_type = st_nevera
        elif "frio" in lname or "frío" in lname:
            loc.storage_type = st_frio
        elif "bodega" in lname:
            loc.storage_type = st_bodega
        else:
            loc.storage_type = default_custom
        loc.save(update_fields=["storage_type"])


def unseed_storage_types_and_backfill_locations(apps, schema_editor):
    StorageType = apps.get_model("inventory", "StorageType")
    Location = apps.get_model("inventory", "Location")

    Location.objects.update(storage_type=None)
    StorageType.objects.filter(
        code__in=[
            "bodega",
            "vitrina",
            "cuarto-frio",
            "nevera",
            "espacio-personalizado",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_update_checkconstraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora de creación (UTC).",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha y hora de última modificación (UTC).",
                    ),
                ),
                ("code", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("category", models.CharField(default="general", max_length=50)),
                ("description", models.TextField(blank=True)),
                ("capabilities", models.JSONField(blank=True, default=dict)),
                ("default_is_retail", models.BooleanField(default=False)),
                ("is_system", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Tipo de almacenamiento",
                "verbose_name_plural": "Tipos de almacenamiento",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.AddField(
            model_name="location",
            name="storage_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locations",
                to="inventory.storagetype",
            ),
        ),
        migrations.RunPython(
            seed_storage_types_and_backfill_locations,
            unseed_storage_types_and_backfill_locations,
        ),
    ]
