# Generated by Django 4.2.30 on 2026-05-31 03:28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_location_relative_capacity"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha y hora de creación (UTC)."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha y hora de última modificación (UTC).",
                    ),
                ),
                ("code", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                ("defaults", models.JSONField(blank=True, default=dict)),
                ("is_system", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "storage_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="templates",
                        to="inventory.storagetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de almacenamiento",
                "verbose_name_plural": "Plantillas de almacenamiento",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.AddField(
            model_name="location",
            name="storage_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locations",
                to="inventory.storagetemplate",
            ),
        ),
    ]
