# Generated by Django 4.2.30 on 2026-06-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_add_location_reorder_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="storagetemplate",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Soft delete timestamp. NULL = activo; not-NULL = eliminado lógicamente.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storagetype",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Soft delete timestamp. NULL = activo; not-NULL = eliminado lógicamente.",
                null=True,
            ),
        ),
    ]
