# Generated by Django 4.2.30 on 2026-06-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0010_add_deleted_at_to_storage_type_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Soft delete timestamp. NULL = activo; not-NULL = eliminado lógicamente.",
                null=True,
            ),
        ),
    ]
