# Generated by Django 4.2.30 on 2026-05-04 17:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Login exitoso'), ('LOGIN_FAILED', 'Login fallido'), ('LOGOUT', 'Cierre de sesión'), ('USER_CREATED', 'Usuario creado'), ('USER_UPDATED', 'Usuario actualizado'), ('USER_DISABLED', 'Usuario deshabilitado'), ('MOVEMENT_CREATED', 'Movimiento creado'), ('ADJUSTMENT_CREATED', 'Ajuste creado'), ('RETURN_CREATED', 'Devolución registrada'), ('REPORT_GENERATED', 'Reporte generado'), ('PERMISSION_CHANGED', 'Permisos modificados'), ('STOCK_RECONSTRUCTED', 'Stock reconstruido desde ledger'), ('PRODUCT_CREATED', 'Producto creado'), ('MOVEMENT_CORRECTED', 'Movimiento corregido (BR-06)'), ('RETURN_APPROVED', 'Devolución aprobada'), ('RETURN_REJECTED', 'Devolución rechazada'), ('ALERT_ACKNOWLEDGED', 'Alerta reconocida'), ('UNAUTHORIZED_ACCESS_ATTEMPT', 'Intento de acceso no autorizado'), ('MODIFICATION_ATTEMPT_ON_IMMUTABLE_RECORD', 'Intento de modificación sobre registro inmutable')], max_length=64)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de auditoría',
                'ordering': ('-created_at',),
            },
        ),
    ]
