# Generated by Django 4.2.30 on 2026-05-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0003_alter_auditlog_event_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLogArchive",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("event_type", models.CharField(max_length=64)),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("movement_id", models.UUIDField(blank=True, null=True)),
                ("description", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Log de Auditoría (Archivo)",
                "verbose_name_plural": "Logs de auditoría (Archivo)",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="audit_audit_created_28cd81_idx"
                    )
                ],
            },
        ),
    ]
