# Generated by Django 5.2.4 on 2026-05-04 23:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación (UTC).')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('requires_serial_number', models.BooleanField(default=False, help_text='BR-04: categoría exige número de serie en entradas/salidas.')),
                ('is_returnable', models.BooleanField(default=False, help_text='BR-05: categoría admite devoluciones (Electroterapia / electrónicos).')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación (UTC).')),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(default='Can', max_length=100)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('weight_grams', models.PositiveIntegerField(blank=True, null=True)),
                ('requires_cold_chain', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('reorder_point', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ComboItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación (UTC).')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_memberships', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Ítem de combo',
                'verbose_name_plural': 'Ítems de combo',
            },
        ),
        migrations.CreateModel(
            name='ProductCombo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación (UTC).')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(related_name='product_combos', through='catalog.ComboItem', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Combo de productos',
                'verbose_name_plural': 'Combos de productos',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='comboitem',
            name='combo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_items', to='catalog.productcombo'),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación (UTC).')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Subcategoría',
                'verbose_name_plural': 'Subcategorías',
                'ordering': ('category_id', 'name'),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.subcategory'),
        ),
        migrations.AddConstraint(
            model_name='comboitem',
            constraint=models.UniqueConstraint(fields=('combo', 'product'), name='uniq_combo_product_item'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('category', 'slug'), name='uniq_subcategory_slug_per_category'),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'name')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='catalog_pro_sku_2c4c34_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='catalog_pro_barcode_58f8f8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='catalog_pro_categor_7c1c1f_idx'),
        ),
    ]
