# Generated by Django 4.2.30 on 2026-05-31

from django.db import connection, migrations


def add_pg_trgm(apps, schema_editor):
    """Agrega extensión pg_trgm e índices GIN solo en PostgreSQL."""
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    schema_editor.execute(
        "CREATE INDEX IF NOT EXISTS catalog_product_name_trgm_idx "
        "ON catalog_product USING GIN (name gin_trgm_ops);"
    )
    schema_editor.execute(
        "CREATE INDEX IF NOT EXISTS catalog_product_sku_trgm_idx "
        "ON catalog_product USING GIN (sku gin_trgm_ops);"
    )


def remove_pg_trgm(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("DROP INDEX IF EXISTS catalog_product_name_trgm_idx;")
    schema_editor.execute("DROP INDEX IF EXISTS catalog_product_sku_trgm_idx;")


class Migration(migrations.Migration):
    """Agrega extensión pg_trgm e índices GIN para búsqueda full-text eficiente (M-01).

    Solo se ejecuta en PostgreSQL; en SQLite es un no-op.
    """

    dependencies = [
        ("catalog", "0003_backfill_product_barcodes"),
    ]

    operations = [
        migrations.RunPython(add_pg_trgm, reverse_code=remove_pg_trgm),
    ]
