# Generated by Django 4.2.30 on 2026-06-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_combo_pricing"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="productpricehistory",
            new_name="catalog_pro_product_0b2827_idx",
            old_name="catalog_pph_prod_field_idx",
        ),
        migrations.AlterField(
            model_name="productpricehistory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Fecha y hora de creación (UTC)."
            ),
        ),
        migrations.AlterField(
            model_name="productpricehistory",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Fecha y hora de última modificación (UTC)."
            ),
        ),
    ]
