# Generated by Django 4.2.30 on 2026-06-12 20:02

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "movements",
            "0007_rename_movements_invoice_number_idx_movements_i_number_dec47a_idx_and_more",
        ),
        ("inventory", "0009_add_location_reorder_point"),
        ("catalog", "0010_barcode_equals_sku"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSerial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha y hora de creación (UTC)."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha y hora de última modificación (UTC).",
                    ),
                ),
                ("serial_number", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Disponible"),
                            ("dispatched", "Despachado"),
                            ("damaged", "Dañado"),
                            ("adjusted", "Ajustado"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "current_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_serials",
                        to="inventory.location",
                    ),
                ),
                (
                    "last_movement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_serial_records",
                        to="movements.movement",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="serials",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Serial de producto",
                "verbose_name_plural": "Seriales de producto",
                "ordering": ("created_at",),
                "indexes": [
                    models.Index(
                        fields=["product", "status"],
                        name="catalog_pro_product_dc02fa_idx",
                    ),
                    models.Index(
                        fields=["current_location", "status"],
                        name="catalog_pro_current_20fd3e_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="productserial",
            constraint=models.UniqueConstraint(
                fields=("product", "serial_number"),
                name="uniq_product_serial_per_product",
            ),
        ),
    ]
