# Generated by Django 4.2.30 on 2026-06-12 21:52

from django.db import migrations


def create_brands_and_migrate(apps, schema_editor):
    """Crea Brands desde Subcategories y migra Product.brand (CharField)
    y subcategory -> Brand FK."""
    Subcategory = apps.get_model("catalog", "Subcategory")
    Brand = apps.get_model("catalog", "Brand")
    Product = apps.get_model("catalog", "Product")

    # 1. Crear Brand por cada Subcategory existente
    for subcat in Subcategory.objects.all():
        Brand.objects.get_or_create(
            name=subcat.name,
            defaults={
                "slug": subcat.slug,
                "description": subcat.description,
                "is_active": subcat.is_active,
            },
        )

    # 2. Crear Brands para los valores únicos existentes en
    # Product.brand (CharField)
    # Obtener valores únicos no nulos del campo brand actual
    existing_brands = set(
        Product.objects.exclude(brand__isnull=True)
        .exclude(brand="")
        .values_list("brand", flat=True)
        .distinct()
    )
    for brand_name in existing_brands:
        Brand.objects.get_or_create(
            name=brand_name,
            defaults={
                "slug": brand_name.lower().replace(" ", "-"),
                "description": "",
                "is_active": True,
            },
        )


def reverse_migrate(apps, schema_editor):
    """No hay reversión realista para esta migración de datos."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_convert_subcategory_to_brand"),
    ]

    operations = [
        migrations.RunPython(create_brands_and_migrate, reverse_migrate),
    ]
