# Generated by Django 4.2.30 on 2026-06-12 21:54

import django.db.models.deletion
from django.db import migrations, models


def migrate_brand_fk(apps, schema_editor):
    """Migra Product.brand (CharField) y subcategory -> brand_fk (FK)."""
    Brand = apps.get_model("catalog", "Brand")
    Product = apps.get_model("catalog", "Product")

    # Migrar productos que tienen brand (CharField) pero no brand_fk
    for product in (
        Product.objects.filter(brand_fk__isnull=True)
        .exclude(brand__isnull=True)
        .exclude(brand="")
    ):
        brand_obj = Brand.objects.filter(name=product.brand).first()
        if brand_obj:
            product.brand_fk = brand_obj
            product.save(update_fields=["brand_fk"])

    # Migrar productos que tienen subcategory pero no brand_fk
    for product in Product.objects.filter(brand_fk__isnull=True).exclude(
        subcategory__isnull=True
    ):
        # Obtener la marca asociada a la subcategoría
        subcat = product.subcategory
        brand_obj = Brand.objects.filter(name=subcat.name).first()
        if brand_obj:
            product.brand_fk = brand_obj
            product.save(update_fields=["brand_fk"])


def reverse_migrate(apps, schema_editor):
    """No hay reversión realista."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0013_migrate_brand_data"),
    ]

    operations = [
        # 1. Añadir campo FK temporal brand_fk
        migrations.AddField(
            model_name="product",
            name="brand_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products_fk",
                to="catalog.brand",
            ),
        ),
        # 2. Migrar datos
        migrations.RunPython(migrate_brand_fk, reverse_migrate),
        # 3. Eliminar campo brand (CharField) y subcategory
        migrations.RemoveField(
            model_name="product",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="product",
            name="subcategory",
        ),
        # 4. Renombrar brand_fk a brand
        migrations.RenameField(
            model_name="product",
            old_name="brand_fk",
            new_name="brand",
        ),
        # 5. Cambiar related_name de products_fk a products
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="catalog.brand",
            ),
        ),
        # 6. Eliminar modelo Subcategory
        migrations.DeleteModel(
            name="Subcategory",
        ),
    ]
