# Generated by Django 4.2.30 on 2026-06-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0015_category_brand_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcombo",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Soft delete timestamp. NULL = activo; not-NULL = eliminado lógicamente.",
                null=True,
            ),
        ),
    ]
