# Generated by Django 4.2.30 on 2026-06-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0016_add_deleted_at_to_combo"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Soft delete timestamp. NULL = activo; not-NULL = eliminado lógicamente.",
                null=True,
            ),
        ),
    ]
