# Generated by Django 4.2.30 on 2026-06-14 19:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0017_add_deleted_at_to_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productcombo",
            name="is_active",
        ),
    ]
