"""Tests de transformación de filas validadas."""

from __future__ import annotations

import pytest

from scripts.import_catalog.reader import RawRow
from scripts.import_catalog.transformer import (
    ImportRow,
    _autogen_sku,
    _transform_invalid_sku,
    transform,
)
from scripts.import_catalog.validator import validate


def make_row(
    codigo: str = "CM-01",
    producto: str = "Camilla Test",
    sheet: str = "Camillas",
    numero: int = 1,
) -> RawRow:
    return RawRow(sheet_name=sheet, codigo=codigo, numero=numero, producto=producto)


class TestAutogenSku:
    def test_flexbar_amarillo_genera_fl_0032(self):
        row = make_row("S/C", producto="Flexbar Amarillo- ICMTHERAPY", numero=32)
        assert _autogen_sku(row) == "FL-0032"

    def test_flexbar_azul_genera_fl_0033(self):
        row = make_row("S/C", producto="Flexbar Azul- ICMTHERAPY", numero=33)
        assert _autogen_sku(row) == "FL-0033"

    def test_usa_primeras_dos_letras_del_primer_word(self):
        row = make_row("S/C", producto="Camilla Portatil", numero=5)
        assert _autogen_sku(row) == "CA-0005"

    def test_numero_con_zero_padding_a_4_digitos(self):
        row = make_row("S/C", producto="Test Producto", numero=1)
        sku = _autogen_sku(row)
        partes = sku.split("-")
        assert len(partes[1]) == 4

    def test_numero_none_usa_1(self):
        row = make_row("S/C", producto="Flexbar", numero=None)
        sku = _autogen_sku(row)
        assert sku.endswith("-0001")


class TestTransformInvalidSku:
    def test_mpc_01a_becomes_mpca_01(self):
        assert _transform_invalid_sku(make_row("MPC-01A")) == "MPCA-01"

    def test_mpc_02a_becomes_mpca_02(self):
        assert _transform_invalid_sku(make_row("MPC-02A")) == "MPCA-02"

    def test_ec_01b_becomes_ecb_01(self):
        assert _transform_invalid_sku(make_row("EC-01b")) == "ECB-01"

    def test_suffix_uppercased(self):
        result = _transform_invalid_sku(make_row("AB-01c"))
        assert result == "ABC-01"

    def test_no_suffix_returns_normalized_sku(self):
        # SKU sin sufijo letra pero con padding incorrecto debería funcionar igual
        result = _transform_invalid_sku(make_row("CM-1"))
        # CM-1 ya es válido, pero _transform_invalid_sku solo se llama para inválidos
        # Si se llama con un sku sin sufijo letra, retorna el mismo SKU normalizado
        assert result == "CM-01"

    def test_returns_none_for_untransformable(self):
        # Sin guion — no se puede parsear
        assert _transform_invalid_sku(make_row("ABCDE01")) is None

    def test_result_passes_sku_validation(self):
        import re

        SKU_SAFE = re.compile(r"^[A-Za-z]{1,4}-\d{1,4}$")
        for codigo in ("MPC-01A", "MPC-02A", "EC-01b"):
            result = _transform_invalid_sku(make_row(codigo))
            assert result is not None
            assert SKU_SAFE.match(result), f"SKU transformado inválido: {result!r}"


class TestTransform:
    def test_valid_rows_pass_through_unchanged(self):
        row = make_row("CM-01", producto="Camilla Test", sheet="Camillas")
        report = validate([row])
        import_rows, errors = transform(report)
        assert len(import_rows) == 1
        assert import_rows[0].sku == "CM-01"
        assert not import_rows[0].sku_was_generated
        assert not import_rows[0].sku_was_transformed
        assert not errors

    def test_sc_rows_get_autogenerated_sku(self):
        row = make_row(
            "S/C",
            producto="Flexbar Amarillo- ICMTHERAPY",
            numero=32,
            sheet="Terapias de Mano",
        )
        report = validate([row])
        import_rows, errors = transform(report)
        assert len(import_rows) == 1
        assert import_rows[0].sku == "FL-0032"
        assert import_rows[0].sku_was_generated
        assert import_rows[0].original_sku == "S/C"

    def test_invalid_sku_gets_transformed(self):
        row = make_row("MPC-01A", producto="Masajeador Talla L", sheet="Masajeadores")
        report = validate([row])
        import_rows, errors = transform(report)
        assert len(import_rows) == 1
        assert import_rows[0].sku == "MPCA-01"
        assert import_rows[0].sku_was_transformed
        assert import_rows[0].original_sku == "MPC-01A"
        assert not errors

    def test_category_name_is_titlecased(self):
        row = make_row("CM-01", producto="Test", sheet="CAMILLAS")
        report = validate([row])
        import_rows, _ = transform(report)
        assert import_rows[0].category_name == "Camillas"

    def test_name_is_stripped(self):
        row = make_row("CM-01", producto="  Camilla con espacios  ", sheet="Camillas")
        report = validate([row])
        import_rows, _ = transform(report)
        assert import_rows[0].name == "Camilla con espacios"

    def test_all_three_invalid_skus_from_excel(self):
        rows = [
            make_row("MPC-01A", producto="Masajeador Talla L", sheet="Masajeadores"),
            make_row(
                "MPC-02A", producto="Masajeador Brazos Talla L", sheet="Masajeadores"
            ),
            make_row("EC-01b", producto="Pesas Tobillo", sheet="Accesorios"),
        ]
        report = validate(rows)
        import_rows, errors = transform(report)
        assert len(import_rows) == 3
        assert not errors
        skus = {r.sku for r in import_rows}
        assert skus == {"MPCA-01", "MPCA-02", "ECB-01"}
