# Generated by Django 4.2.30 on 2026-06-02 18:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("morning_start", models.TimeField(blank=True, null=True)),
                ("morning_end", models.TimeField(blank=True, null=True)),
                ("afternoon_start", models.TimeField(blank=True, null=True)),
                ("afternoon_end", models.TimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_schedule",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Horario de Usuario",
                "verbose_name_plural": "Horarios de Usuarios",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="authenticat_user_id_0b9bf3_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TemporaryAccessPermit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("allow_24_7", models.BooleanField(default=False)),
                ("custom_morning_start", models.TimeField(blank=True, null=True)),
                ("custom_morning_end", models.TimeField(blank=True, null=True)),
                ("custom_afternoon_start", models.TimeField(blank=True, null=True)),
                ("custom_afternoon_end", models.TimeField(blank=True, null=True)),
                ("reason", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_permits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temporary_permits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Permiso Temporal de Acceso",
                "verbose_name_plural": "Permisos Temporales de Acceso",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active", "start_datetime", "end_datetime"],
                        name="authenticat_user_id_8fc1df_idx",
                    )
                ],
            },
        ),
    ]
