# Generated by Django 4.2.30 on 2026-06-11 15:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_passwordresettoken"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="passwordresettoken",
            new_name="authenticat_token_h_499884_idx",
            old_name="authenticat_token_h_idx",
        ),
        migrations.RenameIndex(
            model_name="passwordresettoken",
            new_name="authenticat_user_id_382da0_idx",
            old_name="authenticat_user_used_expires_idx",
        ),
    ]
